// controllers/countryController.js
const allCountryAPI = (req, res) => {
  const allCountries = [
    {
      id: 1,
      country: "United States",
      states: [
        "Alabama",
        "Alaska",
        "Arizona",
        "Arkansas",
        "California",
        "Colorado",
        "Connecticut",
        "Delaware",
        "Florida",
        "Georgia",
        "Hawaii",
        "Idaho",
        "Illinois",
        "Indiana",
        "Iowa",
        "Kansas",
        "Kentucky",
        "Louisiana",
        "Maine",
        "Maryland",
        "Massachusetts",
        "Michigan",
        "Minnesota",
        "Mississippi",
        "Missouri",
        "Montana",
        "Nebraska",
        "Nevada",
        "New Hampshire",
        "New Jersey",
        "New Mexico",
        "New York",
        "North Carolina",
        "North Dakota",
        "Ohio",
        "Oklahoma",
        "Oregon",
        "Pennsylvania",
        "Rhode Island",
        "South Carolina",
        "South Dakota",
        "Tennessee",
        "Texas",
        "Utah",
        "Vermont",
        "Virginia",
        "Washington",
        "West Virginia",
        "Wisconsin",
        "Wyoming",
      ],
    },
    {
      id: 2,
      country: "Canada",
      states: [
        "Alberta",
        "British Columbia",
        "Manitoba",
        "New Brunswick",
        "Newfoundland and Labrador",
        "Nova Scotia",
        "Ontario",
        "Prince Edward Island",
        "Quebec",
        "Saskatchewan",
      ],
    },
    {
      id: 3,
      country: "Australia",
      states: [
        "New South Wales",
        "Queensland",
        "South Australia",
        "Tasmania",
        "Victoria",
        "Western Australia",
      ],
    },
    {
      id: 4,
      country: "Germany",
      states: [
        "Bavaria",
        "Berlin",
        "Brandenburg",
        "Bremen",
        "Hamburg",
        "Hesse",
        "Lower Saxony",
        "Mecklenburg-Vorpommern",
        "North Rhine-Westphalia",
        "Rhineland-Palatinate",
        "Saarland",
        "Saxony",
        "Saxony-Anhalt",
        "Thuringia",
      ],
    },
    {
      id: 5,
      country: "France",
      states: [
        "Île-de-France",
        "Auvergne-Rhône-Alpes",
        "Bourgogne-Franche-Comté",
        "Bretagne",
        "Centre-Val de Loire",
        "Corse",
        "Grand Est",
        "Hauts-de-France",
        "Normandie",
        "Nouvelle-Aquitaine",
        "Occitanie",
        "Pays de la Loire",
        "Provence-Alpes-Côte d'Azur",
      ],
    },
    {
      id: 6,
      country: "Italy",
      states: [
        "Lombardy",
        "Lazio",
        "Campania",
        "Sicily",
        "Veneto",
        "Piedmont",
        "Emilia-Romagna",
        "Tuscany",
        "Calabria",
        "Liguria",
        "Marches",
        "Umbria",
        "Aosta Valley",
        "Trentino-Alto Adige",
        "Apulia",
        "Basilicata",
        "Molise",
        "Sardinia",
        "Friuli Venezia Giulia",
        "Abruzzo",
      ],
    },
    {
      id: 7,
      country: "Spain",
      states: [
        "Madrid",
        "Catalonia",
        "Andalusia",
        "Valencia",
        "Galicia",
        "Castile and León",
        "Basque Country",
        "Canary Islands",
        "Castilla-La Mancha",
        "Murcia",
        "Aragon",
        "Extremadura",
        "Balearic Islands",
        "La Rioja",
        "Navarre",
        "Ceuta",
        "Melilla",
      ],
    },
    {
      id: 8,
      country: "Portugal",
      states: [
        "Lisbon",
        "Porto",
        "Vila Nova de Gaia",
        "Amadora",
        "Braga",
        "Setubal",
        "Coimbra",
        "Queluz",
        "Funchal",
        "Cacem",
      ],
    },
    {
      id: 9,
      country: "Netherlands",
      states: [
        "North Holland",
        "South Holland",
        "North Brabant",
        "Gelderland",
        "Utrecht",
        "Overijssel",
        "Limburg",
        "Flevoland",
        "Groningen",
        "Drenthe",
      ],
    },
    {
      id: 10,
      country: "Belgium",
      states: [
        "Antwerp",
        "East Flanders",
        "West Flanders",
        "Hainaut",
        "Liège",
        "Limburg",
        "Luxembourg",
        "Namur",
      ],
    },
    // First 10 countries

    {
      id: 11,
      country: "United Kingdom",
      states: ["England", "Scotland", "Wales", "Northern Ireland"],
    },
    {
      id: 12,
      country: "Japan",
      states: [
        "Hokkaido",
        "Aomori",
        "Iwate",
        "Miyagi",
        "Akita",
        "Yamagata",
        "Fukushima",
        "Ibaraki",
        "Tochigi",
        "Gunma",
        "Saitama",
        "Chiba",
        "Tokyo",
        "Kanagawa",
        "Niigata",
        "Toyama",
        "Ishikawa",
        "Fukui",
        "Yamanashi",
        "Nagano",
        "Gifu",
        "Shizuoka",
        "Aichi",
        "Mie",
        "Shiga",
        "Kyoto",
        "Osaka",
        "Hyogo",
        "Nara",
        "Wakayama",
        "Tottori",
        "Shimane",
        "Okayama",
        "Hiroshima",
        "Yamaguchi",
        "Tokushima",
        "Kagawa",
        "Ehime",
        "Kochi",
        "Fukuoka",
        "Saga",
        "Nagasaki",
        "Kumamoto",
        "Oita",
        "Miyazaki",
        "Kagoshima",
        "Okinawa",
      ],
    },
    {
      id: 13,
      country: "South Korea",
      states: [
        "Seoul",
        "Busan",
        "Daegu",
        "Incheon",
        "Gwangju",
        "Daejeon",
        "Ulsan",
        "Sejong",
        "Gyeonggi",
        "Gangwon",
        "Chungbuk",
        "Chungnam",
        "Jeonbuk",
        "Jeonnam",
        "Gyeongbuk",
        "Gyeongnam",
        "Jeju",
      ],
    },
    {
      id: 14,
      country: "India",
      states: [
        "Andhra Pradesh",
        "Arunachal Pradesh",
        "Assam",
        "Bihar",
        "Chhattisgarh",
        "Goa",
        "Gujarat",
        "Haryana",
        "Himachal Pradesh",
        "Jharkhand",
        "Karnataka",
        "Kerala",
        "Madhya Pradesh",
        "Maharashtra",
        "Manipur",
        "Meghalaya",
        "Mizoram",
        "Nagaland",
        "Odisha",
        "Punjab",
        "Rajasthan",
        "Sikkim",
        "Tamil Nadu",
        "Telangana",
        "Tripura",
        "Uttar Pradesh",
        "Uttarakhand",
        "West Bengal",
      ],
    },
    {
      id: 15,
      country: "China",
      states: [
        "Beijing",
        "Tianjin",
        "Shanghai",
        "Chongqing",
        "Hebei",
        "Shanxi",
        "Liaoning",
        "Jilin",
        "Heilongjiang",
        "Jiangsu",
        "Zhejiang",
        "Anhui",
        "Fujian",
        "Jiangxi",
        "Shandong",
        "Henan",
        "Hubei",
        "Hunan",
        "Guangdong",
        "Guangxi",
        "Hainan",
        "Chongqing",
        "Sichuan",
        "Guizhou",
        "Yunnan",
        "Tibet",
        "Shaanxi",
        "Gansu",
        "Qinghai",
        "Ningxia",
        "Xinjiang",
      ],
    },
    {
      id: 16,
      country: "Brazil",
      states: [
        "Acre",
        "Alagoas",
        "Amapá",
        "Amazonas",
        "Bahia",
        "Ceará",
        "Distrito Federal",
        "Espírito Santo",
        "Goiás",
        "Maranhão",
        "Mato Grosso",
        "Mato Grosso do Sul",
        "Minas Gerais",
        "Pará",
        "Paraíba",
        "Paraná",
        "Pernambuco",
        "Piauí",
        "Rio de Janeiro",
        "Rio Grande do Norte",
        "Rio Grande do Sul",
        "Rondônia",
        "Roraima",
        "Santa Catarina",
        "São Paulo",
        "Sergipe",
        "Tocantins",
      ],
    },
    {
      id: 17,
      country: "Mexico",
      states: [
        "Aguascalientes",
        "Baja California",
        "Baja California Sur",
        "Campeche",
        "Chiapas",
        "Chihuahua",
        "Coahuila",
        "Colima",
        "Durango",
        "Guanajuato",
        "Guerrero",
        "Hidalgo",
        "Jalisco",
        "Mexico",
        "Mexico City",
        "Michoacán",
        "Morelos",
        "Nayarit",
        "Nuevo León",
        "Oaxaca",
        "Puebla",
        "Querétaro",
        "Quintana Roo",
        "San Luis Potosí",
        "Sinaloa",
        "Sonora",
        "Tabasco",
        "Tamaulipas",
        "Tlaxcala",
        "Veracruz",
        "Yucatán",
        "Zacatecas",
      ],
    },
    {
      id: 18,
      country: "Russia",
      states: [
        "Adygea",
        "Altai",
        "Bashkortostan",
        "Buryatia",
        "Chechnya",
        "Chuvashia",
        "Dagestan",
        "Ingushetia",
        "Kabardino-Balkaria",
        "Kalmykia",
        "Karelia",
        "Komi",
        "Mari El",
        "Mordovia",
        "North Ossetia-Alania",
        "Tatarstan",
        "Tuva",
        "Yakutia",
        "Amur",
        "Arkhangelsk",
        "Astrakhan",
        "Belgorod",
        "Bryansk",
        "Chelyabinsk",
        "Chukotka",
        "Irkutsk",
        "Ivanovo",
        "Kaliningrad",
        "Kaluga",
        "Kamchatka",
        "Kemerovo",
        "Khabarovsk",
        "Kostroma",
        "Kursk",
        "Leningrad",
        "Lipetsk",
        "Magadan",
        "Moscow",
        "Murmansk",
        "Nizhny Novgorod",
        "Novgorod",
        "Novosibirsk",
        "Omsk",
        "Orenburg",
        "Oryol",
        "Penza",
        "Perm",
        "Pskov",
        "Rostov",
        "Ryazan",
        "Saint Petersburg",
        "Sakhalin",
        "Samara",
        "Saratov",
        "Smolensk",
        "Stavropol",
        "Tambov",
        "Tver",
        "Tomsk",
        "Tula",
        "Tyumen",
        "Vladimir",
        "Volgograd",
        "Vologda",
        "Voronezh",
        "Yaroslavl",
        "Zabaykalsky",
      ],
    },
    {
      id: 19,
      country: "South Africa",
      states: [
        "Eastern Cape",
        "Free State",
        "Gauteng",
        "KwaZulu-Natal",
        "Limpopo",
        "Mpumalanga",
        "Northern Cape",
        "North West",
        "Western Cape",
      ],
    },
    {
      id: 20,
      country: "Argentina",
      states: [
        "Buenos Aires",
        "Catamarca",
        "Chaco",
        "Chubut",
        "CABA",
        "Córdoba",
        "Corrientes",
        "Entre Ríos",
        "Formosa",
        "Jujuy",
        "La Pampa",
        "La Rioja",
        "Mendoza",
        "Misiones",
        "Neuquén",
        "Río Negro",
        "Salta",
        "San Juan",
        "San Luis",
        "Santa Cruz",
        "Santa Fe",
        "Santiago del Estero",
        "Tierra del Fuego",
        "Tucumán",
      ],
    },

    // First 20 countries

    {
      id: 21,
      country: "Turkey",
      states: [
        "Adana",
        "Adıyaman",
        "Afyonkarahisar",
        "Ağrı",
        "Aksaray",
        "Amasya",
        "Ankara",
        "Antalya",
        "Ardahan",
        "Artvin",
        "Aydın",
        "Balıkesir",
        "Bartın",
        "Batman",
        "Bayburt",
        "Bilecik",
        "Bingöl",
        "Bitlis",
        "Bolu",
        "Burdur",
        "Bursa",
        "Çanakkale",
        "Çankırı",
        "Çorum",
        "Denizli",
        "Diyarbakır",
        "Düzce",
        "Edirne",
        "Elazığ",
        "Erzincan",
        "Erzurum",
        "Eskişehir",
        "Gaziantep",
        "Giresun",
        "Gümüşhane",
        "Hakkari",
        "Hatay",
        "Iğdır",
        "Isparta",
        "İstanbul",
        "İzmir",
        "Kahramanmaraş",
        "Karabük",
        "Karaman",
        "Kars",
        "Kastamonu",
        "Kayseri",
        "Kırıkkale",
        "Kırklareli",
        "Kırşehir",
        "Kilis",
        "Kocaeli",
        "Konya",
        "Kütahya",
        "Malatya",
        "Manisa",
        "Mardin",
        "Mersin",
        "Muğla",
        "Muş",
        "Nevşehir",
        "Niğde",
        "Ordu",
        "Osmaniye",
        "Rize",
        "Sakarya",
        "Samsun",
        "Sanlıurfa",
        "Siirt",
        "Sinop",
        "Sivas",
        "Şanlıurfa",
        "Şırnak",
        "Tekirdağ",
        "Tokat",
        "Trabzon",
        "Tunceli",
        "Uşak",
        "Van",
        "Yalova",
        "Yozgat",
        "Zonguldak",
      ],
    },
    {
      id: 22,
      country: "Colombia",
      states: [
        "Amazonas",
        "Antioquia",
        "Arauca",
        "Atlántico",
        "Bogotá",
        "Bolívar",
        "Boyacá",
        "Caldas",
        "Caquetá",
        "Casanare",
        "Cauca",
        "Cesar",
        "Chocó",
        "Córdoba",
        "Cundinamarca",
        "Guainía",
        "Guaviare",
        "Guajira",
        "Huila",
        "La Guajira",
        "Magdalena",
        "Meta",
        "Nariño",
        "Norte de Santander",
        "Putumayo",
        "Quindío",
        "Risaralda",
        "San Andrés y Providencia",
        "Santander",
        "Sucre",
        "Tolima",
        "Valle del Cauca",
        "Vaupés",
        "Vichada",
      ],
    },
    {
      id: 23,
      country: "Peru",
      states: [
        "Amazonas",
        "Áncash",
        "Apurímac",
        "Arequipa",
        "Ayacucho",
        "Cajamarca",
        "Callao",
        "Cusco",
        "Huancavelica",
        "Huánuco",
        "Ica",
        "Junín",
        "La Libertad",
        "Lambayeque",
        "Lima",
        "Loreto",
        "Madre de Dios",
        "Moquegua",
        "Pasco",
        "Piura",
        "Puno",
        "San Martín",
        "Tacna",
        "Tumbes",
        "Ucayali",
      ],
    },
    {
      id: 24,
      country: "Venezuela",
      states: [
        "Amazonas",
        "Anzoátegui",
        "Apure",
        "Aragua",
        "Barinas",
        "Bolívar",
        "Carabobo",
        "Cojedes",
        "Delta Amacuro",
        "Falcón",
        "Guárico",
        "Lara",
        "Mérida",
        "Miranda",
        "Monagas",
        "Nueva Esparta",
        "Portuguesa",
        "Sucre",
        "Táchira",
        "Trujillo",
        "Yaracuy",
        "Zulia",
      ],
    },
    {
      id: 25,
      country: "Chile",
      states: [
        "Arica and Parinacota",
        "Atacama",
        "Antofagasta",
        "Coquimbo",
        "Valparaíso",
        "O'Higgins",
        "Maule",
        "Ñuble",
        "Biobío",
        "La Araucanía",
        "Los Ríos",
        "Los Lagos",
        "Aysén",
        "Magallanes",
      ],
    },
    {
      id: 26,
      country: "Ukraine",
      states: [
        "Cherkasy",
        "Chernihiv",
        "Chernivtsi",
        "Crimea",
        "Dnipropetrovsk",
        "Donetsk",
        "Ivano-Frankivsk",
        "Kharkiv",
        "Kherson",
        "Khmelnytskyi",
        "Kiev",
        "Kirovohrad",
        "Luhansk",
        "Lviv",
        "Mykolaiv",
        "Odesa",
        "Poltava",
        "Rivne",
        "Sevastopol",
        "Sumy",
        "Ternopil",
        "Vinnytsia",
        "Volyn",
        "Zakarpattia",
        "Zaporizhzhia",
        "Zhytomyr",
      ],
    },
    {
      id: 27,
      country: "Poland",
      states: [
        "Dolnośląskie",
        "Kujawsko-Pomorskie",
        "Lubusz",
        "Łódź",
        "Małopolskie",
        "Mazowieckie",
        "Opolskie",
        "Podkarpackie",
        "Podlaskie",
        "Pomorskie",
        "Śląskie",
        "Świętokrzyskie",
        "Warmińsko-Mazurskie",
        "Wielkopolskie",
        "Zachodniopomorskie",
      ],
    },
    {
      id: 28,
      country: "Sweden",
      states: [
        "Stockholm",
        "Västra Götaland",
        "Skåne",
        "Uppsala",
        "Östergötland",
        "Örebro",
        "Halland",
        "Jönköping",
        "Kronoberg",
        "Kalmar",
        "Värmland",
        "Dalarna",
        "Gävleborg",
        "Västernorrland",
        "Västerbotten",
        "Norrbotten",
      ],
    },
    {
      id: 29,
      country: "Norway",
      states: [
        "Oslo",
        "Viken",
        "Vestfold og Telemark",
        "Agder",
        "Rogaland",
        "Hedmark",
        "Oppland",
        "Buskerud",
        "Akershus",
        "Sogn og Fjordane",
        "Møre og Romsdal",
        "Trøndelag",
        "Nordland",
        "Troms",
        "Finnmark",
      ],
    },
    {
      id: 30,
      country: "Finland",
      states: [
        "Uusimaa",
        "Varsinais-Suomi",
        "Satakunta",
        "Kanta-Häme",
        "Pirkanmaa",
        "Päijät-Häme",
        "Kymenlaakso",
        "Etelä-Karjala",
        "Pohjois-Karjala",
        "Central Finland",
        "South Ostrobothnia",
        "Ostrobothnia",
        "North Ostrobothnia",
        "Kainuu",
        "Lapland",
      ],
    },

    // First 30 countries

    {
      id: 31,
      country: "Denmark",
      states: [
        "Hovedstaden",
        "Midtjylland",
        "Nordjylland",
        "Syddanmark",
        "Sjælland",
      ],
    },
    {
      id: 32,
      country: "Austria",
      states: [
        "Burgenland",
        "Kärnten",
        "Niederösterreich",
        "Oberösterreich",
        "Salzburg",
        "Steiermark",
        "Tirol",
        "Vorarlberg",
        "Wien",
      ],
    },
    {
      id: 33,
      country: "Kiribati",
      states: [
        "Bairiki",
        "Banaba",
        "Betio",
        "Kiritimati",
        "Tabiteuea",
        "Teraina",
      ],
    },
    {
      id: 34,
      country: "Switzerland",
      states: [
        "Aargau",
        "Appenzell Ausserrhoden",
        "Appenzell Innerrhoden",
        "Basel-Landschaft",
        "Basel-Stadt",
        "Bern",
        "Fribourg",
        "Geneva",
        "Glarus",
        "Graubünden",
        "Jura",
        "Lucerne",
        "Neuchâtel",
        "Nidwalden",
        "Obwalden",
        "Schaffhausen",
        "Schwyz",
        "Solothurn",
        "St. Gallen",
        "Thurgau",
        "Ticino",
        "Uri",
        "Valais",
        "Vaud",
        "Zug",
        "Zurich",
      ],
    },
    {
      id: 35,
      country: "Ireland",
      states: [
        "Dublin",
        "Cork",
        "Limerick",
        "Galway",
        "Waterford",
        "Kildare",
        "Kilkenny",
        "Mayo",
        "Meath",
        "Monaghan",
        "Offaly",
        "Roscommon",
        "Tipperary",
        "Wexford",
        "Westmeath",
        "Wicklow",
      ],
    },
    {
      id: 36,
      country: "Nauru",
      states: [
        "Aiwo",
        "Anabar",
        "Anetan",
        "Anibare",
        "Boe",
        "Buada",
        "Denigomodu",
        "Ewa",
        "Ijuw",
        "Meneng",
        "Nauru",
        "Uaboe",
        "Yaren",
      ],
    },
    {
      id: 37,
      country: "New Zealand",
      states: [
        "Auckland",
        "Bay of Plenty",
        "Canterbury",
        "Gisborne",
        "Hawke's Bay",
        "Manawatu-Wanganui",
        "Marlborough",
        "Nelson",
        "Northland",
        "Otago",
        "Southland",
        "Taranaki",
        "Waikato",
        "Wellington",
        "West Coast",
      ],
    },
    {
      id: 38,
      country: "Singapore",
      states: ["Central", "East", "North", "North-East", "West"],
    },
    {
      id: 39,
      country: "Malaysia",
      states: [
        "Johor",
        "Kedah",
        "Kelantan",
        "Malacca",
        "Negeri Sembilan",
        "Pahang",
        "Perak",
        "Perlis",
        "Penang",
        "Sabah",
        "Sarawak",
        "Wilayah Persekutuan Kuala Lumpur",
        "Wilayah Persekutuan Labuan",
        "Wilayah Persekutuan Putrajaya",
      ],
    },
    {
      id: 40,
      country: "Philippines",
      states: [
        "Abra",
        "Agusan del Norte",
        "Agusan del Sur",
        "Aklan",
        "Albay",
        "Antique",
        "Apayao",
        "Aurora",
        "Basilan",
        "Bataan",
        "Batanes",
        "Batangas",
        "Benguet",
        "Biliran",
        "Bohol",
        "Bukidnon",
        "Bulacan",
        "Cagayan",
        "Camarines Norte",
        "Camarines Sur",
        "Camiguin",
        "Capiz",
        "Catanduanes",
        "Cavite",
        "Cebu",
        "Compostela Valley",
        "Cotabato",
        "Davao del Norte",
        "Davao del Sur",
        "Davao Occidental",
        "Davao Oriental",
        "Eastern Samar",
        "Guimaras",
        "Ifugao",
        "Ilocos Norte",
        "Ilocos Sur",
        "Iloilo",
        "Isabela",
        "Kalinga",
        "Kalibo",
        "La Union",
        "Laguna",
        "Lanao del Norte",
        "Lanao del Sur",
        "Leyte",
        "Maguindanao",
        "Marinduque",
        "Masbate",
        "Misamis Occidental",
        "Misamis Oriental",
        "Mountain Province",
        "Negros Occidental",
        "Negros Oriental",
        "Northern Samar",
        "Nueva Ecija",
        "Nueva Vizcaya",
        "Occidental Mindoro",
        "Oriental Mindoro",
        "Palawan",
        "Pampanga",
        "Pangasinan",
        "Quezon",
        "Quirino",
        "Rizal",
        "Romblon",
        "Samar",
        "Sarangani",
        "Siquijor",
        "Sorsogon",
        "South Cotabato",
        "Southern Leyte",
        "Sultan Kudarat",
        "Sulu",
        "Surigao del Norte",
        "Surigao del Sur",
        "Tarlac",
        "Tawi-Tawi",
        "Zambales",
        "Zamboanga del Norte",
        "Zamboanga del Sur",
        "Zamboanga Sibugay",
      ],
    },

    // First 40 countries

    {
      id: 41,
      country: "Tuvalu",
      states: [
        "Funafuti",
        "Nanumea",
        "Nanumaga",
        "Niutao",
        "Nui",
        "Vaitupu",
        "Wallis",
      ],
    },
    {
      id: 42,
      country: "Nigeria",
      states: [
        "Abia",
        "Adamawa",
        "Akwa Ibom",
        "Anambra",
        "Bauchi",
        "Bayelsa",
        "Benue",
        "Borno",
        "Cross River",
        "Delta",
        "Ebonyi",
        "Edo",
        "Ekiti",
        "Enugu",
        "Gombe",
        "Imo",
        "Jigawa",
        "Kaduna",
        "Kano",
        "Katsina",
        "Kebbi",
        "Kogi",
        "Kwara",
        "Lagos",
        "Nasarawa",
        "Niger",
        "Ogun",
        "Ondo",
        "Osun",
        "Oyo",
        "Plateau",
        "Rivers",
        "Sokoto",
        "Taraba",
        "Yobe",
        "Zamfara",
      ],
    },
    {
      id: 43,
      country: "Egypt",
      states: [
        "Cairo",
        "Alexandria",
        "Giza",
        "Port Said",
        "Suez",
        "Shubra El Kheima",
        "Mansoura",
        "Tanta",
        "Asyut",
        "Ismailia",
        "Beni Suef",
        "Faiyum",
        "Damanhur",
        "Kafr el-Sheikh",
        "Minya",
        "Aswan",
        "Qena",
        "Luxor",
        "Matruh",
        "New Valley",
      ],
    },
    {
      id: 44,
      country: "Iran",
      states: [
        "Alborz",
        "Ardabil",
        "Bushehr",
        "Chaharmahal and Bakhtiari",
        "East Azerbaijan",
        "Fars",
        "Gilan",
        "Golestan",
        "Hamedan",
        "Hormozgan",
        "Ilam",
        "Isfahan",
        "Kerman",
        "Kermanshah",
        "Khuzestan",
        "Kohgiluyeh and Boyer-Ahmad",
        "Kurdistan",
        "Lorestan",
        "Markazi",
        "Mazandaran",
        "North Khorasan",
        "Qazvin",
        "Qom",
        "Razavi Khorasan",
        "Semnan",
        "Sistan and Baluchestan",
        "South Khorasan",
        "Tehran",
        "Yazd",
        "Zanjan",
      ],
    },
    {
      id: 45,
      country: "Thailand",
      states: [
        "Bangkok",
        "Chiang Mai",
        "Chiang Rai",
        "Chonburi",
        "Khon Kaen",
        "Lampang",
        "Lopburi",
        "Nakhon Nayok",
        "Nakhon Pathom",
        "Nakhon Ratchasima",
        "Nakhon Si Thammarat",
        "Narathiwat",
        "Nonthaburi",
        "Pattani",
        "Phayao",
        "Phatthalung",
        "Phitsanulok",
        "Prachuap Khiri Khan",
        "Prachinburi",
        "Rayong",
        "Roi Et",
        "Sa Kaeo",
        "Sakon Nakhon",
        "Samut Prakan",
        "Samut Sakhon",
        "Samut Songkhram",
        "Saraburi",
        "Singburi",
        "Sukhothai",
        "Suphan Buri",
        "Surat Thani",
        "Surin",
        "Trang",
        "Trat",
        "Ubon Ratchathani",
        "Udon Thani",
        "Uttaradit",
        "Yala",
        "Yasothon",
      ],
    },
    {
      id: 46,
      country: "Vanuatu",
      states: ["Malampa", "Penama", "Sanma", "Shefa", "Tafea", "Torba"],
    },
    {
      id: 47,
      country: "Pakistan",
      states: [
        "Azad Jammu and Kashmir",
        "Balochistan",
        "Federally Administered Tribal Areas",
        "Gilgit-Baltistan",
        "Khyber Pakhtunkhwa",
        "Punjab",
        "Sindh",
      ],
    },
    {
      id: 48,
      country: "Saudi Arabia",
      states: [
        "Riyadh",
        "Mecca",
        "Medina",
        "Eastern Province",
        "Asir",
        "Tabuk",
        "Hail",
        "Jizan",
        "Najran",
        "Al Bahah",
        "Al Jawf",
        "Northern Borders",
      ],
    },
    {
      id: 49,
      country: "United Arab Emirates",
      states: [
        "Abu Dhabi",
        "Dubai",
        "Sharjah",
        "Ajman",
        "Umm Al-Quwain",
        "Fujairah",
        "Ras Al Khaimah",
      ],
    },
    {
      id: 50,
      country: "Iraq",
      states: [
        "Baghdad",
        "Basra",
        "Dhi Qar",
        "Diyala",
        "Kirkuk",
        "Muthanna",
        "Najaf",
        "Nineveh",
        "Qadisiyyah",
        "Saladin",
        "Sulaymaniyah",
        "Wasit",
        "Erbil",
        "Karbala",
      ],
    },

    // First 50 countries

    {
      id: 51,
      country: "Jordan",
      states: [
        "Amman",
        "Irbid",
        "Zarqa",
        "Balqa",
        "Mafraq",
        "Karak",
        "Ma'an",
        "Ajloun",
        "Tafilah",
        "Jerar",
      ],
    },
    {
      id: 52,
      country: "Lebanon",
      states: [
        "Beirut",
        "Mount Lebanon",
        "North Governorate",
        "South Governorate",
        "Bekaa",
      ],
    },
    {
      id: 53,
      country: "Syria",
      states: [
        "Damascus",
        "Aleppo",
        "Homs",
        "Latakia",
        "Deir ez-Zor",
        "Hasakah",
        "Daraa",
        "Rif Dimashq",
        "Quneitra",
        "Idlib",
        "Tartus",
      ],
    },
    {
      id: 54,
      country: "Oman",
      states: [
        "Muscat",
        "Dhofar",
        "Dakhiliyah",
        "Batinah",
        "Sharqiyah",
        "Buraimi",
        "Musandam",
        "North Sharqiyah",
        "South Sharqiyah",
      ],
    },
    {
      id: 55,
      country: "Kuwait",
      states: ["Al Asimah", "Hawalli", "Mubarak Al-Kabeer", "Ahmadi", "Jahra"],
    },
    {
      id: 56,
      country: "Bahrain",
      states: [
        "Capital Governorate",
        "Muharraq",
        "Northern Governorate",
        "Southern Governorate",
      ],
    },
    {
      id: 57,
      country: "Qatar",
      states: [
        "Doha",
        "Al Rayyan",
        "Al Wakrah",
        "Umm Salal",
        "Al Khor",
        "Al Daayen",
        "Al Shamal",
        "Madinat ash Shamal",
        "Al Jufairah",
        "Al Zubara",
      ],
    },
    {
      id: 58,
      country: "Sri Lanka",
      states: [
        "Western Province",
        "Central Province",
        "Southern Province",
        "Northern Province",
        "Eastern Province",
        "North Western Province",
        "North Central Province",
        "Uva Province",
        "Sabaragamuwa Province",
      ],
    },
    {
      id: 59,
      country: "Nepal",
      states: [
        "Province No. 1",
        "Province No. 2",
        "Bagmati",
        "Gandaki",
        "Lumbini",
        "Karnali",
        "Sudurpashchim",
      ],
    },
    {
      id: 60,
      country: "Bhutan",
      states: [
        "Thimphu",
        "Chukha",
        "Dagana",
        "Gasa",
        "Haa",
        "Paro",
        "Punakha",
        "Wangdue Phodrang",
        "Zhemgang",
        "Samdrup Jongkhar",
        "Trashigang",
        "Trashiyangtse",
      ],
    },

    // First 60 countries

    {
      id: 61,
      country: "Afghanistan",
      states: [
        "Badakhshan",
        "Badghis",
        "Baghlan",
        "Balkh",
        "Bamyan",
        "Daykundi",
        "Farah",
        "Faryab",
        "Ghazni",
        "Ghor",
        "Helmand",
        "Herat",
        "Jowzjan",
        "Kabul",
        "Kandahar",
        "Kapisa",
        "Khost",
        "Kunar",
        "Kunduz",
        "Laghman",
        "Logar",
        "Nangarhar",
        "Nimroz",
        "Nuristan",
        "Paktia",
        "Paktika",
        "Panjsher",
        "Samangan",
        "Sar-e Pol",
        "Takhar",
        "Urozgan",
        "Wardak",
        "Zabul",
      ],
    },
    {
      id: 62,
      country: "Albania",
      states: [
        "Berat",
        "Diber",
        "Durres",
        "Elbasan",
        "Shkoder",
        "Fier",
        "Korçe",
        "Tirane",
      ],
    },
    {
      id: 63,
      country: "Algeria",
      states: [
        "Adrar",
        "Chlef",
        "Laghouat",
        "Oum El Bouaghi",
        "Batna",
        "Béjaïa",
        "Biskra",
        "Bordj Bou Arréridj",
        "Bouira",
        "Tamanrasset",
        "Tébessa",
        "Tlemcen",
        "Tiaret",
        "Tizi Ouzou",
        "Algiers",
        "Djelfa",
        "Jijel",
        "Sétif",
        "Saïda",
        "Skikda",
        "Sidi Bel Abbès",
        "Annaba",
        "Guelma",
        "Constantine",
        "Médéa",
        "Mostaganem",
        "M'sila",
        "Mascara",
        "Ouargla",
        "Oran",
        "El Bayadh",
        "El Oued",
        "El M'ghair",
        "El Menia",
        "Touggourt",
        "Djanet",
        "In Salah",
        "In Guezzam",
        "El Agheila",
        "Illizi",
        "Tindouf",
      ],
    },
    {
      id: 64,
      country: "Andorra",
      states: [
        "Andorra la Vella",
        "Escaldes-Engordany",
        "Encamp",
        "Ordino",
        "Canillo",
        "Sant Julià de Lòria",
      ],
    },
    {
      id: 65,
      country: "Angola",
      states: [
        "Bengo",
        "Benguela",
        "Bié",
        "Cabinda",
        "Cuando Cubango",
        "Cuanza Norte",
        "Cuanza Sul",
        "Cunene",
        "Huambo",
        "Huíla",
        "Luanda",
        "Lunda Norte",
        "Lunda Sul",
        "Malanje",
        "Moxico",
        "Namibe",
        "Uíge",
        "Zaire",
      ],
    },
    {
      id: 66,
      country: "Antigua and Barbuda",
      states: [
        "Saint John's",
        "Saint George",
        "Saint Peter",
        "Saint Paul",
        "Saint Mary",
        "Saint Philip",
        "Barbuda",
      ],
    },
    {
      id: 67,
      country: "Armenia",
      states: [
        "Aragatsotn",
        "Ararat",
        "Armavir",
        "Gegharkunik",
        "Kotayk",
        "Lori",
        "Shirak",
        "Syunik",
        "Vayots Dzor",
        "Yerevan",
      ],
    },
    {
      id: 68,
      country: "Azerbaijan",
      states: [
        "Absheron",
        "Agdam",
        "Agjabadi",
        "Agstafa",
        "Agsu",
        "Astara",
        "Baku",
        "Beylagan",
        "Bilasuvar",
        "Ganja",
        "Goranboy",
        "Goychay",
        "Goygol",
        "Lankaran",
        "Lankaran",
        "Mingachevir",
        "Naftalan",
        "Sabirabad",
        "Salyan",
        "Shaki",
        "Shamkir",
        "Shusha",
        "Sumqayit",
        "Tartar",
        "Tovuz",
        "Yardimli",
      ],
    },
    {
      id: 69,
      country: "Bahamas",
      states: [
        "Acklins and Crooked Islands",
        "Berry Islands",
        "Bimini",
        "Cat Island",
        "Exuma",
        "Grand Bahama",
        "Inagua",
        "Long Island",
        "New Providence",
        "Ragged Island",
        "San Salvador and Rum Cay",
      ],
    },
    {
      id: 70,
      country: "Barbados",
      states: [
        "Christ Church",
        "Saint Andrew",
        "Saint George",
        "Saint James",
        "Saint John",
        "Saint Joseph",
        "Saint Lucy",
        "Saint Michael",
        "Saint Peter",
        "Saint Philip",
        "Saint Thomas",
      ],
    },

    // First 70 countries

    {
      id: 71,
      country: "Belarus",
      states: ["Brest", "Gomel", "Grodno", "Minsk", "Mogilev", "Vitebsk"],
    },
    {
      id: 72,
      country: "Belize",
      states: [
        "Belize District",
        "Cayo District",
        "Corozal District",
        "Orange Walk District",
        "Stann Creek District",
        "Toledo District",
      ],
    },
    {
      id: 73,
      country: "Benin",
      states: [
        "Alibori",
        "Atakora",
        "Atlantique",
        "Borgou",
        "Collines",
        "Donga",
        "Kouffo",
        "Littoral",
        "Mono",
        "Ouémé",
        "Plateau",
        "Zou",
      ],
    },
    {
      id: 74,
      country: "Bolivia",
      states: [
        "Beni",
        "Chuquisaca",
        "Cochabamba",
        "La Paz",
        "Oruro",
        "Pando",
        "Potosí",
        "Santa Cruz",
        "Tarija",
      ],
    },
    {
      id: 75,
      country: "Bosnia and Herzegovina",
      states: [
        "Federation of Bosnia and Herzegovina",
        "Republika Srpska",
        "Brčko District",
      ],
    },
    {
      id: 76,
      country: "Botswana",
      states: [
        "Central",
        "Gaborone",
        "Ghanzi",
        "Kgalagadi",
        "Kgatleng",
        "Kweneng",
        "Ngamiland",
        "North-East",
        "South-East",
        "Southern",
      ],
    },
    {
      id: 77,
      country: "Brunei",
      states: ["Brunei-Muara", "Belait", "Tutong", "Lumut"],
    },
    {
      id: 78,
      country: "Bulgaria",
      states: [
        "Blagoevgrad",
        "Burgas",
        "Dobrich",
        "Gabrovo",
        "Haskovo",
        "Kardzhali",
        "Kyustendil",
        "Lovech",
        "Montana",
        "Pazardzhik",
        "Pernik",
        "Pleven",
        "Plovdiv",
        "Razgrad",
        "Ruse",
        "Shumen",
        "Silistra",
        "Sliven",
        "Smolyan",
        "Sofia",
        "Sofia City",
        "Stara Zagora",
        "Targovishte",
        "Varna",
        "Veliko Tarnovo",
        "Vidin",
        "Vratsa",
      ],
    },
    {
      id: 79,
      country: "Burkina Faso",
      states: [
        "Boucle du Mouhoun",
        "Cascades",
        "Centre",
        "Centre-East",
        "Centre-North",
        "Centre-West",
        "East",
        "North",
        "North-Central",
        "North-East",
        "Sahel",
        "South",
        "South-West",
      ],
    },
    {
      id: 80,
      country: "Burundi",
      states: [
        "Bubanza",
        "Bujumbura",
        "Bujumbura Rural",
        "Bururi",
        "Cibitoke",
        "Cankuzo",
        "Gitega",
        "Karuzi",
        "Kayanza",
        "Kirundo",
        "Makamba",
        "Muramvya",
        "Muyinga",
        "Mwaro",
        "Ngozi",
        "Rutana",
        "Ruyigi",
      ],
    },

    // First 80 countries

    {
      id: 81,
      country: "Cabo Verde",
      states: [
        "Boa Vista",
        "Brava",
        "Fogo",
        "Maio",
        "Santiago",
        "Santa Luzia",
        "São Nicolau",
        "São Vicente",
      ],
    },
    {
      id: 82,
      country: "Cambodia",
      states: [
        "Banteay Meanchey",
        "Battambang",
        "Kampong Cham",
        "Kampong Chhnang",
        "Kampong Speu",
        "Kampong Thom",
        "Kampot",
        "Kandal",
        "Kep",
        "Koh Kong",
        "Kratie",
        "Mondulkiri",
        "Phnom Penh",
        "Preah Vihear",
        "Prey Veng",
        "Pursat",
        "Ratanakiri",
        "Siem Reap",
        "Sihanoukville",
        "Svay Rieng",
        "Takeo",
        "Tboung Khmum",
      ],
    },
    {
      id: 83,
      country: "Cameroon",
      states: [
        "Adamawa",
        "Centre",
        "East",
        "Far North",
        "North",
        "North West",
        "South",
        "South West",
      ],
    },
    {
      id: 84,
      country: "Central African Republic",
      states: [
        "Bamingui-Bangoran",
        "Basse-Kotto",
        "Haute-Kotto",
        "Haute-Sangha",
        "Kemo",
        "Lobaye",
        "Mambere-Kadeï",
        "Nana-Mambéré",
        "Ombella-M'Poko",
        "Ouaka",
        "Ouham",
        "Ouham-Pende",
        "Sangha-Mbaéré",
        "Vakaga",
      ],
    },
    {
      id: 85,
      country: "Chad",
      states: [
        "Chari-Baguirmi",
        "Guéra",
        "Kanem",
        "Lac",
        "Logone Occidental",
        "Logone Oriental",
        "Mayo-Kebbi Est",
        "Mayo-Kebbi Ouest",
        "Middle Chari",
        "N'Djamena",
        "Sila",
        "Tandjilé",
        "Tibesti",
        "Wadi Fira",
      ],
    },
    {
      id: 86,
      country: "Comoros",
      states: ["Anjouan", "Grande Comore", "Moheli"],
    },
    {
      id: 87,
      country: "Congo (Congo-Brazzaville)",
      states: [
        "Bouenza",
        "Brazzaville",
        "Cuvette",
        "Cuvette-Ouest",
        "Kouilou",
        "Lekoumou",
        "Likouala",
        "Niari",
        "Plateaux",
        "Pointe-Noire",
        "Sangha",
      ],
    },
    {
      id: 88,
      country: "Costa Rica",
      states: [
        "Alajuela",
        "Cartago",
        "Guanacaste",
        "Heredia",
        "Limón",
        "Puntarenas",
        "San José",
      ],
    },
    {
      id: 89,
      country: "Croatia",
      states: [
        "Bjelovar-Bilogora",
        "Brodsko-Posavska",
        "Dubrovnik-Neretva",
        "Istria",
        "Karlovac",
        "Koprivnica-Križevci",
        "Krapina-Zagorje",
        "Lika-Senj",
        "Međimurje",
        "Osijek-Baranja",
        "Požega-Slavonia",
        "Primorje-Gorski Kotar",
        "Sisak-Moslavina",
        "Split-Dalmatia",
        "Varaždin",
        "Virovitica-Podravina",
        "Vukovar-Srijem",
        "Zadar",
        "Zagreb",
        "Zagreb City",
      ],
    },
    {
      id: 90,
      country: "Cuba",
      states: [
        "Pinar del Río",
        "Havana",
        "Matanzas",
        "Cienfuegos",
        "Villa Clara",
        "Sancti Spíritus",
        "Ciego de Ávila",
        "Camagüey",
        "Las Tunas",
        "Holguín",
        "Guantánamo",
        "Santiago de Cuba",
      ],
    },

    // First 90 countries

    {
      id: 91,
      country: "Cyprus",
      states: [
        "Famagusta",
        "Kyrenia",
        "Larnaca",
        "Limassol",
        "Nicosia",
        "Paphos",
      ],
    },
    {
      id: 92,
      country: "Czechia (Czech Republic)",
      states: [
        "Prague",
        "Central Bohemian",
        "South Bohemian",
        "Plzeň",
        "Karlovy Vary",
        "Ústí nad Labem",
        "Liberec",
        "Hradec Králové",
        "Pardubice",
        "Olomouc",
        "Zlin",
        "South Moravian",
        "North Moravian",
      ],
    },
    {
      id: 93,
      country: "Djibouti",
      states: [
        "Ali Sabieh",
        "Dikhil",
        "Djibouti",
        "Arta",
        "Tadjourah",
        "Obock",
      ],
    },
    {
      id: 94,
      country: "Dominica",
      states: [
        "Saint George",
        "Saint John",
        "Saint Joseph",
        "Saint Luke",
        "Saint Mark",
        "Saint Patrick",
        "Saint Paul",
        "Saint David",
      ],
    },
    {
      id: 95,
      country: "Dominican Republic",
      states: [
        "Azua",
        "Baoruco",
        "Barahona",
        "Dajabón",
        "Distrito Nacional",
        "Duarte",
        "El Seibo",
        "Elías Piña",
        "Espaillat",
        "La Altagracia",
        "La Romana",
        "La Vega",
        "María Trinidad Sánchez",
        "Monseñor Nouel",
        "Monte Cristi",
        "Monte Plata",
        "Pedernales",
        "Peravia",
        "Puerto Plata",
        "Samaná",
        "San Cristóbal",
        "San José de Ocoa",
        "San Juan",
        "San Pedro de Macorís",
        "Santiago",
        "Santiago Rodríguez",
        "Valverde",
      ],
    },
    {
      id: 96,
      country: "East Timor (Timor-Leste)",
      states: [
        "Aileu",
        "Ainaro",
        "Baucau",
        "Bobonaro",
        "Covalima",
        "Dili",
        "Ermera",
        "Lautém",
        "Liquiçá",
        "Manatuto",
        "Manufahi",
        "Oecusse",
        "Viqueque",
      ],
    },
    {
      id: 97,
      country: "Equatorial Guinea",
      states: [
        "Annobón",
        "Bioko Norte",
        "Bioko Sur",
        "Centro Sur",
        "Kie-Ntem",
        "Litoral",
        "Wele-Nzas",
      ],
    },
    {
      id: 98,
      country: "Eritrea",
      states: [
        "Anseba",
        "Debub",
        "Debubawi Keyih Bahri",
        "Maekel",
        "Semien Keih Bahri",
        "Southern Red Sea",
      ],
    },
    {
      id: 99,
      country: "Estonia",
      states: [
        "Harju",
        "Hiiu",
        "Ida-Viru",
        "Jõgeva",
        "Järva",
        "Lääne",
        "Lääne-Viru",
        "Põlva",
        "Pärnu",
        "Rapla",
        "Saare",
        "Tartu",
        "Valga",
        "Viljandi",
        "Võru",
      ],
    },
    {
      id: 100,
      country: 'Eswatini (fmr. "Swaziland")',
      states: ["Hhohho", "Lubombo", "Manzini", "Shiselweni"],
    },

    // First 100 countries

    {
      id: 101,
      country: "Vatican City (Holy See)",
      states: ["Vatican City"],
    },
    {
      id: 102,
      country: "Western Sahara (Disputed status)",
      states: ["Aousserd", "Boujdour", "Dakhla", "El Ayoun", "Smara"],
    },
    
    {
      id: 103,
      country: "Gabon",
      states: [
        "Estuaire",
        "Haut-Ogooué",
        "Moyen-Ogooué",
        "Ngounié",
        "Ogooué-Ivindo",
        "Ogooué-Lolo",
        "Ogooué-Maritime",
        "Woleu-Ntem",
      ],
    },
    {
      id: 104,
      country: "Guatemala",
      states: [
        "Alta Verapaz",
        "Baja Verapaz",
        "Chimaltenango",
        "Chiquimula",
        "El Progreso",
        "Escuintla",
        "Guatemala",
        "Huehuetenango",
        "Izabal",
        "Jalapa",
        "Jutiapa",
        "Peten",
        "Quiché",
        "Quetzaltenango",
        "Retalhuleu",
        "Sacatepéquez",
        "San Marcos",
        "Santa Rosa",
        "Solalá",
        "Suchitepéquez",
        "Totonicapan",
        "Zacapa",
      ],
    },
    {
      id: 105,
      country: "Honduras",
      states: [
        "Atlántida",
        "Choluteca",
        "Colón",
        "Comayagua",
        "Copán",
        "Cortés",
        "Distrito Central",
        "El Paraíso",
        "Francisco Morazán",
        "Gracias a Dios",
        "Islas de la Bahía",
        "La Paz",
        "Lempira",
        "Ocotepeque",
        "Olancho",
        "Santa Bárbara",
        "Yoro",
      ],
    },
    {
      id: 106,
      country: "Iceland",
      states: [
        "Höfuðborgarsvæði",
        "Vesturland",
        "Vestfirðir",
        "Norðurland Eystra",
        "Norðurland Vestra",
        "Suðurland",
        "Suðurnes",
      ],
    },
    {
      id: 107,
      country: "Laos",
      states: [
        "Attapeu",
        "Champasak",
        "Houaphanh",
        "Khammouane",
        "Luang Namtha",
        "Luang Prabang",
        "Oudomxay",
        "Phongsali",
        "Savannakhet",
        "Sekong",
        "Xaisomboun",
        "Xekong",
        "Xieng Khouang",
        "Vientiane",
        "Vientiane Prefecture",
        "Borikhamxai",
      ],
    },
    {
      id: 108,
      country: "Moldova",
      states: [
        "Bălți",
        "Bender",
        "Briceni",
        "Cahul",
        "Căușeni",
        "Chişinău",
        "Drochia",
        "Edineț",
        "Nisporeni",
        "Rîșcani",
        "Soroca",
        "Strășeni",
        "Telenești",
        "Ungheni",
        "Ialoveni",
        "Orhei",
        "Ștefan Vodă",
      ],
    },
    {
      id: 109,
      country: "Mongolia",
      states: [
        "Arhangai",
        "Bayan-Ölgii",
        "Bayanhör",
        "Dornod",
        "Dornogovi",
        "Dundgovi",
        "Dzavhan",
        "Govi-Altai",
        "Govisümber",
        "Khentii",
        "Khovd",
        "Khuvsgul",
        "Ovorhangai",
        "Sükhbaatar",
        "Töv",
        "Ulaanbaatar",
        "Uvs",
        "Zavkhan",
      ],
    },
    {
      id: 110,
      country: "Palau",
      states: [
        "Aimeliik",
        "Airai",
        "Angaur",
        "Babeldaob",
        "Kayangel",
        "Koror",
        "Peleliu",
        "Sonsorol",
      ],
    },

    // First 110 countries

    {
      id: 111,
      country: "Panama",
      states: [
        "Bocas del Toro",
        "Chiriquí",
        "Coclé",
        "Colón",
        "Darién",
        "Emberá",
        "Guna Yala",
        "Herrera",
        "Los Santos",
        "Panamá",
        "Panamá Oeste",
        "Veraguas",
      ],
    },
    {
      id: 112,
      country: "Paraguay",
      states: [
        "Alto Paraguay",
        "Alto Paraná",
        "Boquerón",
        "Caaguazú",
        "Caazapá",
        "Central",
        "Concepción",
        "Cordillera",
        "Guairá",
        "Itapúa",
        "Misiones",
        "Ñeembucú",
        "Paraguarí",
        "Presidente Hayes",
        "San Pedro",
      ],
    },
    {
      id: 113,
      country: "Papua New Guinea",
      states: [
        "Central",
        "Chimbu",
        "Eastern Highlands",
        "Eastern New Britain",
        "Enga",
        "Gulf",
        "Madang",
        "Manus",
        "Milne Bay",
        "Morobe",
        "New Ireland",
        "Northern",
        "Pomio",
        "Southern Highlands",
        "West New Britain",
        "West Sepik",
        "Western",
      ],
    },
    {
      id: 114,
      country: "Rwanda",
      states: [
        "Bugesera",
        "Burera",
        "Byumba",
        "Gakenke",
        "Gatsibo",
        "Gicumbi",
        "Gisenyi",
        "Gitarama",
        "Gitega",
        "Kigali",
        "Kigali Rural",
        "Kirehe",
        "Kisoro",
        "Muhanga",
        "Musanze",
        "Ngoma",
        "Nyaruguru",
        "Nyamagabe",
        "Nyamasheke",
        "Nyanza",
        "Nyeri",
        "Rubavu",
        "Rutsiro",
        "Rulindo",
        "Rusizi",
        "Rwanda",
        "Rwanda (District)",
      ],
    },
    {
      id: 115,
      country: "Saint Lucia",
      states: [
        "Castries",
        "Choiseul",
        "Dennery",
        "Gross Islet",
        "Laborie",
        "Micoud",
        "Soufrière",
        "Vieux Fort",
      ],
    },
    {
      id: 116,
      country: "Saint Vincent and the Grenadines",
      states: [
        "Charlotte",
        "Grenadines",
        "Saint Andrew",
        "Saint David",
        "Saint George",
        "Saint Patrick",
      ],
    },
    {
      id: 117,
      country: "Samoa",
      states: [
        "Aiga-i-le-Tai",
        "Atua",
        "Fa’asaleleaga",
        "Falealili",
        "Falealoto",
        "Falealupo",
        "Falealoto",
        "Faleata",
        "Fasitoo-Tai",
        "Vaisigano",
      ],
    },
    {
      id: 118,
      country: "San Marino",
      states: [
        "Acquaviva",
        "Borgo Maggiore",
        "City of San Marino",
        "Domagnano",
        "Faetano",
        "Fiorentino",
        "Montegiardino",
        "Serravalle",
      ],
    },
    {
      id: 119,
      country: "Seychelles",
      states: [
        "Anse Boileau",
        "Anse Etoile",
        "Anse Louis",
        "Anse Royale",
        "Baie Lazare",
        "Baie Sainte Anne",
        "Bel Ombre",
        "Bel Air",
        "Grand Anse",
        "La Digue",
        "Mont Fleuri",
        "Port Glaud",
        "Saint Louis",
        "Takamaka",
      ],
    },
    {
      id: 120,
      country: "Tonga",
      states: ["Ha'apai", "Tongatapu", "Vava'u", "Niuas", "'Eua"],
    },

    // First 120 countries

    {
      id: 121,
      country: "South Sudan",
      states: [
        "Central Equatoria",
        "Eastern Equatoria",
        "Jonglei",
        "Lakes",
        "Northern Bahr el Ghazal",
        "Unity",
        "Upper Nile",
        "Warrap",
        "Western Bahr el Ghazal",
        "Western Equatoria",
      ],
    },
    {
      id: 122,
      country: "Sudan",
      states: [
        "Abyei Area",
        "Blue Nile",
        "Central Darfur",
        "East Darfur",
        "Kassala",
        "Khartoum",
        "North Darfur",
        "North Kordofan",
        "Northern",
        "Red Sea",
        "South Darfur",
        "South Kordofan",
        "West Darfur",
        "West Kordofan",
        "White Nile",
      ],
    },
    {
      id: 123,
      country: "Somalia",
      states: [
        "Awdal",
        "Bakool",
        "Banadir",
        "Bari",
        "Bay",
        "Benaadir",
        "Galgaduud",
        "Gedo",
        "Hiraan",
        "Juba",
        "Lower Juba",
        "Lower Shabelle",
        "Middle Juba",
        "Middle Shabelle",
        "Mudug",
        "Nugaal",
        "Sanaag",
        "Sool",
        "Woqooyi Galbeed",
      ],
    },
    {
      id: 124,
      country: "Yemen",
      states: [
        "Abyan",
        "Ad Dali'",
        "Adan",
        "Al Bayda",
        "Al Hudaydah",
        "Al Jawf",
        "Al Mahrah",
        "Al Mahwit",
        "Amanat al Asimah",
        "Dhamar",
        "Hadramaut",
        "Hajja",
        "Ibb",
        "Lahij",
        "Marib",
        "Raimah",
        "Sana'a",
        "Shabwa",
        "Socotra",
        "Ta'izz",
      ],
    },
    {
      id: 125,
      country: "Libya",
      states: [
        "Ajdabiya",
        "Al Bayda",
        "Al Jabal al Akhdar",
        "Al Jufra",
        "Al Kufrah",
        "Al Marqab",
        "Al Wahat",
        "Banghazi",
        "Darnah",
        "Jabal al Gharbi",
        "Jufra",
        "Murzuq",
        "Sebha",
        "Tripoli",
        "Wadi al Shatii",
        "Zawiya",
        "Zliten",
      ],
    },
    {
      id: 126,
      country: "Mali",
      states: [
        "Bamako",
        "Gao",
        "Kayes",
        "Kidal",
        "Koulikoro",
        "Mopti",
        "Ségou",
        "Sikasso",
        "Tombouctou",
      ],
    },
    {
      id: 127,
      country: "Mauritania",
      states: [
        "Adrar",
        "Assaba",
        "Brakna",
        "Gorgol",
        "Guidimaka",
        "Tagant",
        "Tiris Zemmour",
        "Trarza",
        "Nouakchott",
        "Nouadhibou",
      ],
    },
    {
      id: 128,
      country: "Senegal",
      states: [
        "Dakar",
        "Diourbel",
        "Fatick",
        "Kaolack",
        "Kédougou",
        "Kolda",
        "Louga",
        "Matam",
        "Saint-Louis",
        "Tambacounda",
        "Thiès",
        "Ziguinchor",
      ],
    },
    {
      id: 129,
      country: "Ghana",
      states: [
        "Ashanti",
        "Brong-Ahafo",
        "Central",
        "Eastern",
        "Greater Accra",
        "Northern",
        "Upper East",
        "Upper West",
        "Western",
        "Western North",
      ],
    },
    {
      id: 130,
      country: "Ivory Coast",
      states: [
        "Abidjan",
        "Bas-Sassandra",
        "Comoé",
        "Denguélé",
        "Gôh-Djiboua",
        "Lacs",
        "Lagunes",
        "Montagnes",
        "Sassandra-Marahoué",
        "Vallée du Bandama",
        "Woroba",
        "Zanzan",
      ],
    },

    // First 130 countries

    {
      id: 131,
      country: "Togo",
      states: ["Centrale", "Kara", "Maritime", "Plateaux", "Savanes"],
    },
    {
      id: 132,
      country: "Sierra Leone",
      states: [
        "Eastern Province",
        "Northern Province",
        "Southern Province",
        "Western Area",
      ],
    },
    {
      id: 133,
      country: "Liberia",
      states: [
        "Bong",
        "Bomi",
        "Gbarpolu",
        "Grand Bassa",
        "Grand Cape Mount",
        "Grand Gedeh",
        "Grand Kru",
        "Lofa",
        "Margibi",
        "Montserrado",
        "Nimba",
        "River Cess",
        "River Gee",
        "Sinoe",
      ],
    },
    {
      id: 134,
      country: "Niger",
      states: [
        "Agadez",
        "Diffa",
        "Dosso",
        "Maradi",
        "Niamey",
        "Tahoua",
        "Tillabéri",
        "Zinder",
      ],
    },
    {
      id: 135,
      country: "Guinea",
      states: [
        "Boké",
        "Conakry",
        "Faranah",
        "Kankan",
        "Kindia",
        "Labé",
        "Mamou",
        "Nzérékoré",
      ],
    },
    {
      id: 136,
      country: "Malawi",
      states: [
        "Blantyre",
        "Central Region",
        "Lilongwe",
        "Machinga",
        "Mangochi",
        "Mzuzu",
        "Northern Region",
        "Southern Region",
        "Zomba",
      ],
    },
    {
      id: 137,
      country: "Mozambique",
      states: [
        "Cabo Delgado",
        "Gaza",
        "Inhambane",
        "Manica",
        "Maputo",
        "Nampula",
        "Niassa",
        "Sofala",
        "Tete",
        "Zambézia",
      ],
    },
    {
      id: 138,
      country: "Zambia",
      states: [
        "Central",
        "Copperbelt",
        "Eastern",
        "Luapula",
        "Lusaka",
        "Muchinga",
        "Northern",
        "North-Western",
        "Southern",
        "Western",
      ],
    },
    {
      id: 139,
      country: "Zimbabwe",
      states: [
        "Bulawayo",
        "Harare",
        "Manicaland",
        "Mashonaland Central",
        "Mashonaland East",
        "Mashonaland West",
        "Masvingo",
        "Midlands",
        "Matabeleland North",
        "Matabeleland South",
      ],
    },
    {
      id: 140,
      country: "Lesotho",
      states: [
        "Berea",
        "Butha-Buthe",
        "Leribe",
        "Mafeteng",
        "Maseru",
        "Mohale's Hoek",
        "Mokhotlong",
        "Qacha's Nek",
        "Quthing",
        "Thaba-Tseka",
      ],
    },

    // First 140 countries

    {
      id: 141,
      country: "Mauritius",
      states: [
        "Black River",
        "Flacq",
        "Grand Port",
        "Moka",
        "Pamplemousses",
        "Plaines Wilhems",
        "Port Louis",
        "Rivière du Rempart",
        "Rodrigues",
      ],
    },
    {
      id: 142,
      country: "Grenada",
      states: [
        "Carriacou and Petite Martinique",
        "Saint Andrew",
        "Saint David",
        "Saint George",
        "Saint John",
        "Saint Mark",
        "Saint Patrick",
      ],
    },
    {
      id: 143,
      country: "Solomon Islands",
      states: [
        "Choiseul",
        "Central",
        "Guadalcanal",
        "Honiara",
        "Isabel",
        "Makira-Ulawa",
        "Malaita",
        "Rennell and Bellona",
        "Temotu",
        "Western",
      ],
    },

    {
      id: 144,
      country: "New Caledonia (Special Collectivity of France)",
      states: [
        "Lifou",
        "Maré",
        "Ouvéa",
        "Grande Terre",
        "Îles Loyauté",
        "Île des Pins",
      ],
    },
    
    {
      id: 145,
      country: "Liechtenstein",
      states: [
        "Eschen",
        "Gamprin",
        "Mauren",
        "Nendeln",
        "Schaan",
        "Schellenberg",
        "Ruggell",
        "Vaduz",
        "Balzers",
        "Planken",
      ],
    },
    {
      id: 146,
      country: "Monaco",
      states: [
        "Monaco-Ville",
        "Monte Carlo",
        "La Condamine",
        "Moneghetti",
        "Fontvieille",
        "Les Révoires",
        "Monte Carlo",
      ],
    },
    
    

    // First 150 countries
  ];

  res.json(allCountries);
};

const allCountryDialingCode = (req, res) => {
  const allCountries = [
    {
      id: 1,
      country: "China",
      code: "+86",
    },
    {
      id: 2,
      country: "India",
      code: "+91",
    },
    {
      id: 3,
      country: "United States",
      code: "+1",
    },
    {
      id: 4,
      country: "Indonesia",
      code: "+62",
    },
    {
      id: 5,
      country: "Pakistan",
      code: "+92",
    },
    {
      id: 6,
      country: "Brazil",
      code: "+55",
    },
    {
      id: 7,
      country: "Bangladesh",
      code: "+880",
    },
    {
      id: 8,
      country: "Nigeria",
      code: "+234",
    },
    {
      id: 9,
      country: "Russia",
      code: "+7",
    },
    {
      id: 10,
      country: "Japan",
      code: "+81",
    },
    {
      id: 11,
      country: "Mexico",
      code: "+52",
    },
    {
      id: 12,
      country: "Philippines",
      code: "+63",
    },
    {
      id: 13,
      country: "Vietnam",
      code: "+84",
    },
    {
      id: 14,
      country: "Ethiopia",
      code: "+251",
    },
    {
      id: 15,
      country: "Egypt",
      code: "+20",
    },
    {
      id: 16,
      country: "Germany",
      code: "+49",
    },
    {
      id: 17,
      country: "Iran",
      code: "+98",
    },
    {
      id: 18,
      country: "Turkey",
      code: "+90",
    },
    {
      id: 19,
      country: "Thailand",
      code: "+66",
    },
    {
      id: 20,
      country: "France",
      code: "+33",
    },
    {
      id: 21,
      country: "South Korea",
      code: "+82",
    },
    {
      id: 22,
      country: "Argentina",
      code: "+54",
    },
    {
      id: 23,
      country: "Myanmar",
      code: "+95",
    },
    {
      id: 24,
      country: "Ukraine",
      code: "+380",
    },
    {
      id: 25,
      country: "Sudan",
      code: "+249",
    },
    {
      id: 26,
      country: "Uganda",
      code: "+256",
    },
    {
      id: 27,
      country: "Iraq",
      code: "+964",
    },
    {
      id: 28,
      country: "Poland",
      code: "+48",
    },
    {
      id: 29,
      country: "Canada",
      code: "+1",
    },
    {
      id: 30,
      country: "Malaysia",
      code: "+60",
    },
    {
      id: 31,
      country: "Greece",
      code: "+30",
    },
    {
      id: 32,
      country: "Morocco",
      code: "+212",
    },
    {
      id: 33,
      country: "Saudi Arabia",
      code: "+966",
    },
    {
      id: 34,
      country: "Madagascar",
      code: "+261",
    },
    {
      id: 35,
      country: "Cameroon",
      code: "+237",
    },
    {
      id: 36,
      country: "Cote d'Ivoire",
      code: "+225",
    },
    {
      id: 37,
      country: "Australia",
      code: "+61",
    },
    {
      id: 38,
      country: "Kazakhstan",
      code: "+7",
    },
    {
      id: 39,
      country: "Nepal",
      code: "+977",
    },
    {
      id: 40,
      country: "Zimbabwe",
      code: "+263",
    },
    {
      id: 41,
      country: "Yemen",
      code: "+967",
    },
    {
      id: 42,
      country: "Mozambique",
      code: "+258",
    },
    {
      id: 43,
      country: "Cambodia",
      code: "+855",
    },
    {
      id: 44,
      country: "Senegal",
      code: "+221",
    },
    {
      id: 45,
      country: "Chad",
      code: "+235",
    },
    {
      id: 46,
      country: "Honduras",
      code: "+504",
    },
    {
      id: 47,
      country: "Sierra Leone",
      code: "+232",
    },
    {
      id: 48,
      country: "El Salvador",
      code: "+503",
    },
    {
      id: 49,
      country: "Lebanon",
      code: "+961",
    },
    {
      id: 50,
      country: "Ghana",
      code: "+233",
    },
    {
      id: 51,
      country: "South Africa",
      code: "+27",
    },
    {
      id: 52,
      country: "Kenya",
      code: "+254",
    },
    {
      id: 53,
      country: "Italy",
      code: "+39",
    },
    {
      id: 54,
      country: "Spain",
      code: "+34",
    },
    {
      id: 55,
      country: "Portugal",
      code: "+351",
    },
    {
      id: 56,
      country: "Netherlands",
      code: "+31",
    },
    {
      id: 57,
      country: "Belgium",
      code: "+32",
    },
    {
      id: 58,
      country: "Switzerland",
      code: "+41",
    },
    {
      id: 59,
      country: "Sweden",
      code: "+46",
    },
    {
      id: 60,
      country: "Norway",
      code: "+47",
    },
    {
      id: 61,
      country: "Denmark",
      code: "+45",
    },
    {
      id: 62,
      country: "Finland",
      code: "+358",
    },
    {
      id: 63,
      country: "Ireland",
      code: "+353",
    },
    {
      id: 64,
      country: "New Zealand",
      code: "+64",
    },
    {
      id: 65,
      country: "Austria",
      code: "+43",
    },
    {
      id: 66,
      country: "Hungary",
      code: "+36",
    },
    {
      id: 67,
      country: "Gambia",
      code: "+220",
    },
    {
      id: 68,
      country: "Jamaica",
      code: "+1",
    },
    {
      id: 69,
      country: "Bolivia",
      code: "+591",
    },
    {
      id: 70,
      country: "Ecuador",
      code: "+593",
    },
    {
      id: 71,
      country: "Peru",
      code: "+51",
    },
    {
      id: 72,
      country: "Venezuela",
      code: "+58",
    },
    {
      id: 73,
      country: "Chile",
      code: "+56",
    },
    {
      id: 74,
      country: "Czech Republic",
      code: "+420",
    },
    {
      id: 75,
      country: "Slovakia",
      code: "+421",
    },
    {
      id: 76,
      country: "Singapore",
      code: "+65",
    },
    {
      id: 77,
      country: "Malawi",
      code: "+265",
    },
    {
      id: 78,
      country: "Rwanda",
      code: "+250",
    },
    {
      id: 79,
      country: "Mali",
      code: "+223",
    },
    {
      id: 80,
      country: "Cuba",
      code: "+53",
    },
    {
      id: 81,
      country: "United Kingdom",
      code: "+44",
    },
    {
      id: 82,
      country: "South Sudan",
      code: "+211",
    },
    {
      id: 83,
      country: "Fiji",
      code: "+679",
    },
    {
      id: 84,
      country: "Romania",
      code: "+40",
    },
    {
      id: 85,
      country: "Sri Lanka",
      code: "+94",
    },
    {
      id: 86,
      country: "Tunisia",
      code: "+216",
    },
    {
      id: 87,
      country: "Estonia",
      code: "+372",
    },
    {
      id: 88,
      country: "Niger",
      code: "+227",
    },
    {
      id: 89,
      country: "Botswana",
      code: "+267",
    },
    {
      id: 90,
      country: "Mauritania",
      code: "+222",
    },
    {
      id: 91,
      country: "Cyprus",
      code: "+357",
    },
    {
      id: 92,
      country: "Trinidad and Tobago",
      code: "+1",
    },
    {
      id: 93,
      country: "Barbados",
      code: "+1",
    },
    {
      id: 94,
      country: "Bahrain",
      code: "+973",
    },
    {
      id: 95,
      country: "Luxembourg",
      code: "+352",
    },
    {
      id: 96,
      country: "Liberia",
      code: "+231",
    },
    {
      id: 97,
      country: "Lesotho",
      code: "+266",
    },
    {
      id: 98,
      country: "San Marino",
      code: "+378",
    },
    {
      id: 99,
      country: "Eswatini",
      code: "+268",
    },
  ];

  res.json(allCountries);
};

module.exports = {
  allCountryAPI,
  allCountryDialingCode,
};
