// controllers/countryController.js
const allCountryAPI = (req, res) => {
        const allCountries = [
          {
            id: 1,
            country: "China",
            states: [
              "Beijing",
              "Shanghai",
              "Guangdong",
              "Zhejiang",
              "Fujian",
              "Hubei",
              "Hunan",
              "Sichuan",
              "Jiangsu",
              "Shaanxi",
              "Yunnan",
              "Anhui",
              "Jiangxi",
              "Shandong",
            ],
          },
          {
            id: 2,
            country: "India",
            states: [
              "Uttar Pradesh",
              "Maharashtra",
              "Bihar",
              "West Bengal",
              "Karnataka",
              "Tamil Nadu",
              "Rajasthan",
              "Madhya Pradesh",
              "Gujarat",
              "Andhra Pradesh",
              "Kerala",
              "Telangana",
              "Odisha",
              "Assam",
            ],
          },
          {
            id: 3,
            country: "United States",
            states: [
              "California",
              "Texas",
              "Florida",
              "New York",
              "Illinois",
              "Pennsylvania",
              "Ohio",
              "Georgia",
              "North Carolina",
              "Michigan",
              "New Jersey",
              "Virginia",
              "Arizona",
              "Tennessee",
            ],
          },
          {
            id: 4,
            country: "Indonesia",
            states: [
              "Jakarta",
              "West Java",
              "East Java",
              "Central Java",
              "Bali",
              "North Sumatra",
              "South Sulawesi",
              "Papua",
              "Aceh",
              "Riau",
              "Lampung",
              "West Kalimantan",
              "East Kalimantan",
              "South Kalimantan",
            ],
          },
          {
            id: 5,
            country: "Pakistan",
            states: [
              "Punjab",
              "Sindh",
              "Khyber Pakhtunkhwa",
              "Balochistan",
              "Islamabad Capital Territory",
              "Gilgit-Baltistan",
              "Azad Jammu and Kashmir",
            ],
          },
          {
            id: 6,
            country: "Brazil",
            states: [
              "Sao Paulo",
              "Rio de Janeiro",
              "Minas Gerais",
              "Bahia",
              "Rio Grande do Sul",
              "Parana",
              "Ceara",
              "Pernambuco",
              "Amazonas",
              "Santa Catarina",
              "Goias",
              "Maranhao",
              "Para",
              "Espirito Santo",
            ],
          },
          {
            id: 7,
            country: "Bangladesh",
            states: [
              "Dhaka",
              "Chittagong",
              "Khulna",
              "Rajshahi",
              "Sylhet",
              "Barisal",
              "Rangpur",
            ],
          },
          {
            id: 8,
            country: "Nigeria",
            states: [
              "Lagos",
              "Kano",
              "Kaduna",
              "Oyo",
              "Rivers",
              "Katsina",
              "Benue",
              "Akwa Ibom",
              "Enugu",
              "Delta",
              "Ogun",
              "Anambra",
              "Edo",
              "Niger",
              "Abia",
              "Adamawa",
              "Bauchi",
              "Bayelsa",
              "Borno",
              "Cross River",
              "Ebonyi",
              "Ekiti",
              "Gombe",
              "Imo",
              "Jigawa",
              "Kebbi",
              "Kogi",
              "Osun",
              "Plateau",
              "Sokoto",
              "Taraba",
              "Yobe",
              "Zamfara",
              "Federal Capital Territory (FCT) Abuja",
              "Nasarawa",
              "Kwara",
            ],
          },
          {
            id: 9,
            country: "Russia",
            states: [
              "Moscow",
              "Saint Petersburg",
              "Novosibirsk",
              "Yekaterinburg",
              "Nizhny Novgorod",
              "Kazan",
              "Chelyabinsk",
              "Omsk",
              "Samara",
              "Rostov-on-Don",
              "Ufa",
              "Volgograd",
              "Krasnoyarsk",
              "Voronezh",
            ],
          },
          {
            id: 10,
            country: "Japan",
            states: [
              "Tokyo",
              "Kanagawa",
              "Osaka",
              "Aichi",
              "Saitama",
              "Chiba",
              "Hyogo",
              "Hokkaido",
              "Fukuoka",
              "Shizuoka",
              "Hiroshima",
              "Okayama",
              "Miyagi",
              "Nagasaki",
            ],
          },
          // Add more countries and their states as needed to reach a total of 50 countries.
          {
            id: 11,
            country: "Mexico",
            states: [
              "Mexico City",
              "Jalisco",
              "Nuevo Leon",
              "Guanajuato",
              "Veracruz",
              "Puebla",
              "Tamaulipas",
              "Baja California",
              "Sinaloa",
              "Chihuahua",
              "Michoacan",
              "Sonora",
              "Coahuila",
              "Hidalgo",
            ],
          },
          {
            id: 12,
            country: "Philippines",
            states: [
              "Metro Manila",
              "Calabarzon",
              "Central Luzon",
              "Western Visayas",
              "Eastern Visayas",
              "Central Visayas",
              "Northern Mindanao",
              "Davao Region",
              "Ilocos Region",
              "Cagayan Valley",
              "Zamboanga Peninsula",
              "Caraga",
            ],
          },
          {
            id: 13,
            country: "Vietnam",
            states: [
              "Hanoi",
              "Ho Chi Minh City",
              "Hai Phong",
              "Can Tho",
              "Da Nang",
              "Lam Dong",
              "Quang Ninh",
              "Khanh Hoa",
              "Binh Duong",
              "Thua Thien-Hue",
              "Ba Ria-Vung Tau",
              "Tay Ninh",
              "Dong Nai",
              "Long An",
            ],
          },
          {
            id: 14,
            country: "Ethiopia",
            states: [
              "Oromia",
              "Amhara",
              "Southern Nations, Nationalities, and Peoples' Region",
              "Tigray",
              "Somali",
              "Afar",
              "Gambela",
              "Benishangul-Gumuz",
              "Harari",
              "Sidama",
              "SNNPR",
            ],
          },
          {
            id: 15,
            country: "Egypt",
            states: [
              "Cairo",
              "Alexandria",
              "Giza",
              "Faiyum",
              "Suez",
              "Asyut",
              "Minya",
              "Dakahlia",
              "Sharqia",
              "Ismailia",
              "Port Said",
              "Luxor",
              "Qena",
              "Sohag",
            ],
          },
          {
            id: 16,
            country: "Germany",
            states: [
              "Berlin",
              "Bavaria",
              "North Rhine-Westphalia",
              "Baden-Württemberg",
              "Lower Saxony",
              "Hesse",
              "Saxony",
              "Rhineland-Palatinate",
              "Schleswig-Holstein",
              "Thuringia",
              "Brandenburg",
              "Saxony-Anhalt",
              "Saarland",
              "Bremen",
            ],
          },
          {
            id: 17,
            country: "Iran",
            states: [
              "Tehran",
              "Isfahan",
              "Fars",
              "Khorasan Razavi",
              "Khuzestan",
              "East Azerbaijan",
              "West Azerbaijan",
              "Kermanshah",
              "Sistan and Baluchestan",
              "Mazandaran",
              "Gilan",
              "Kerman",
              "Hormozgan",
              "Kurdistan",
            ],
          },
          {
            id: 18,
            country: "Turkey",
            states: [
              "Istanbul",
              "Ankara",
              "Izmir",
              "Bursa",
              "Adana",
              "Konya",
              "Antalya",
              "Mersin",
              "Gaziantep",
              "Diyarbakir",
              "Kayseri",
              "Kocaeli",
              "Samsun",
              "Balikesir",
            ],
          },
          {
            id: 19,
            country: "Thailand",
            states: [
              "Bangkok",
              "Nakhon Ratchasima",
              "Chiang Mai",
              "Udon Thani",
              "Khon Kaen",
              "Nakhon Pathom",
              "Chonburi",
              "Phuket",
              "Surat Thani",
              "Songkhla",
              "Nakhon Sawan",
              "Rayong",
              "Pathum Thani",
              "Ayutthaya",
            ],
          },
          {
            id: 20,
            country: "France",
            states: [
              "Ile-de-France",
              "Auvergne-Rhone-Alpes",
              "Occitanie",
              "Nouvelle-Aquitaine",
              "Hauts-de-France",
              "Provence-Alpes-Cote d'Azur",
              "Brittany",
              "Normandy",
              "Grand Est",
              "Pays de la Loire",
              "Centre-Val de Loire",
              "Bourgogne-Franche-Comte",
              "Corsica",
            ],
          },
          {
            id: 21,
            country: "South Korea",
            states: [
              "Seoul",
              "Busan",
              "Incheon",
              "Gyeonggi",
              "Gangwon",
              "North Chungcheong",
              "South Chungcheong",
              "North Jeolla",
              "South Jeolla",
              "North Gyeongsang",
              "South Gyeongsang",
              "Jeju",
            ],
          },
          {
            id: 22,
            country: "Argentina",
            states: [
              "Buenos Aires",
              "Cordoba",
              "Santa Fe",
              "Mendoza",
              "Tucuman",
              "Entre Rios",
              "Salta",
              "Chaco",
              "Corrientes",
              "Misiones",
              "San Juan",
              "San Luis",
              "La Pampa",
              "Neuquen",
            ],
          },
          {
            id: 23,
            country: "Myanmar",
            states: [
              "Yangon",
              "Mandalay",
              "Naypyidaw",
              "Bago",
              "Magway",
              "Sagaing",
              "Ayeyarwady",
              "Tanintharyi",
              "Chin",
              "Kachin",
              "Kayah",
              "Mon",
              "Rakhine",
              "Shan",
            ],
          },
          {
            id: 24,
            country: "Ukraine",
            states: [
              "Kyiv",
              "Kharkiv",
              "Odesa",
              "Dnipropetrovsk",
              "Donetsk",
              "Zaporizhia",
              "Lviv",
              "Kryvyi Rih",
              "Mykolaiv",
              "Mariupol",
              "Luhansk",
              "Kherson",
              "Vinnytsia",
              "Simferopol",
            ],
          },
          {
            id: 25,
            country: "Sudan",
            states: [
              "Khartoum",
              "Northern",
              "Red Sea",
              "Kassala",
              "Gedaref",
              "Blue Nile",
              "White Nile",
              "Sennar",
              "South Kordofan",
              "North Kordofan",
              "Darfur",
              "West Kordofan",
            ],
          },
          {
            id: 26,
            country: "Uganda",
            states: [
              "Central Region",
              "Eastern Region",
              "Northern Region",
              "Western Region",
            ],
          },
          {
            id: 27,
            country: "Iraq",
            states: [
              "Baghdad",
              "Basra",
              "Mosul",
              "Erbil",
              "Kirkuk",
              "Dhi Qar",
              "Babil",
              "Al Anbar",
              "Najaf",
              "Wasit",
              "Diyala",
              "Saladin",
              "Maysan",
              "Muthanna",
            ],
          },
          {
            id: 28,
            country: "Poland",
            states: [
              "Masovian",
              "Lesser Poland",
              "Silesian",
              "Greater Poland",
              "Lodz",
              "Kuyavian-Pomeranian",
              "Lower Silesian",
              "Lubusz",
              "Podlaskie",
              "Pomeranian",
              "Warmian-Masurian",
              "Subcarpathian",
              "Lublin",
              "Opole",
            ],
          },
          {
            id: 29,
            country: "Canada",
            states: [
              "Ontario",
              "Quebec",
              "British Columbia",
              "Alberta",
              "Manitoba",
              "Saskatchewan",
              "Nova Scotia",
              "New Brunswick",
              "Newfoundland and Labrador",
              "Prince Edward Island",
              "Northwest Territories",
              "Yukon",
              "Nunavut",
            ],
          },
          {
            id: 30,
            country: "Malaysia",
            states: [
              "Selangor",
              "Johor",
              "Penang",
              "Perak",
              "Sarawak",
              "Sabah",
              "Pahang",
              "Negeri Sembilan",
              "Malacca",
              "Kedah",
              "Kelantan",
              "Terengganu",
              "Labuan",
              "Putrajaya",
            ],
          },
          {
            id: 31,
            country: "Greece",
            states: [
              "Attica",
              "Central Macedonia",
              "Crete",
              "Eastern Macedonia and Thrace",
              "Central Greece",
              "Epirus",
              "Ionian Islands",
              "North Aegean",
              "Peloponnese",
              "South Aegean",
              "Thessaly",
              "Western Greece",
              "Western Macedonia",
            ],
          },
          {
            id: 32,
            country: "Morocco",
            states: [
              "Casablanca-Settat",
              "Fes-Meknes",
              "Marrakesh-Safi",
              "Rabat-Sale-Kenitra",
              "Tanger-Tetouan-Al Hoceima",
              "Oriental",
              "Beni Mellal-Khenifra",
              "Souss-Massa",
              "Draa-Tafilalet",
              "Guelmim-Oued Noun",
              "Laayoune-Sakia El Hamra",
              "Dakhla-Oued Ed-Dahab",
            ],
          },
          {
            id: 33,
            country: "Saudi Arabia",
            states: [
              "Riyadh",
              "Makkah",
              "Eastern Province",
              "Asir",
              "Tabuk",
              "Ha'il",
              "Northern Borders",
              "Jazan",
              "Najran",
              "Al Bahah",
              "Al Jawf",
            ],
          },
          {
            id: 34,
            country: "Madagascar",
            states: [
              "Analamanga",
              "Itasy",
              "Bongolava",
              "Vakinankaratra",
              "Amoron'i Mania",
              "Haute Matsiatra",
              "Vatovavy-Fitovinany",
              "Atsimo-Atsinanana",
              "Ihorombe",
              "Menabe",
              "Melaky",
              "Betsiboka",
              "Boeny",
              "Sofia",
              "Diana",
              "Sava",
              "Analanjirofo",
            ],
          },
          {
            id: 35,
            country: "Cameroon",
            states: [
              "Adamawa",
              "Centre",
              "East",
              "Far North",
              "Littoral",
              "North",
              "Northwest",
              "South",
              "Southwest",
              "West",
            ],
          },
          {
            id: 36,
            country: "Cote d'Ivoire",
            states: [
              "Lagunes",
              "Savanes",
              "Vallee du Bandama",
              "Haut-Sassandra",
              "Sud-Bandama",
              "Moyen-Comoe",
              "Denguele",
              "N'zi-Comoe",
              "Marahoue",
              "Woroba",
              "Sud-Comoe",
              "Worodougou",
              "Zanzan",
              "Bas-Sassandra",
            ],
          },
          {
            id: 37,
            country: "Australia",
            states: [
              "New South Wales",
              "Queensland",
              "Victoria",
              "Tasmania",
              "South Australia",
              "Western Australia",
              "Northern Territory",
              "Australian Capital Territory",
            ],
          },
          {
            id: 38,
            country: "Kazakhstan",
            states: [
              "Almaty",
              "Nur-Sultan",
              "Shymkent",
              "East Kazakhstan",
              "Almaty Region",
              "Aktobe",
              "Akmola",
              "Atyrau",
              "West Kazakhstan",
              "Karaganda",
              "Kostanay",
              "Mangystau",
              "Kyzylorda",
              "Pavlodar",
            ],
          },
          {
            id: 39,
            country: "Nepal",
            states: [
              "Bagmati",
              "Gandaki",
              "Karnali",
              "Province No. 1",
              "Province No. 2",
              "Province No. 5",
              "Sudurpashchim",
            ],
          },
          {
            id: 40,
            country: "Zimbabwe",
            states: [
              "Harare",
              "Bulawayo",
              "Mashonaland Central",
              "Mashonaland East",
              "Mashonaland West",
              "Masvingo",
              "Matabeleland North",
              "Matabeleland South",
              "Midlands",
            ],
          },
          {
            id: 41,
            country: "Yemen",
            states: [
              "Sana'a",
              "Aden",
              "Taiz",
              "Al Hudaydah",
              "Ibb",
              "Dhamar",
              "Hadramaut",
              "Al Mahrah",
              "Al Mahwit",
              "Hajjah",
              "Lahij",
              "Abyan",
              "Al Bayda",
              "Al Jawf",
              "Marib",
              "Raymah",
              "Saada",
              "Shabwah",
              "Socotra",
            ],
          },
          {
            id: 42,
            country: "Mozambique",
            states: [
              "Cabo Delgado",
              "Gaza",
              "Inhambane",
              "Manica",
              "Maputo",
              "Nampula",
              "Niassa",
              "Sofala",
              "Tete",
              "Zambezia",
            ],
          },
          {
            id: 43,
            country: "Cambodia",
            states: [
              "Phnom Penh",
              "Kandal",
              "Battambang",
              "Siem Reap",
              "Preah Sihanouk",
              "Kampong Cham",
              "Kampong Speu",
              "Takeo",
              "Kampong Thom",
              "Banteay Meanchey",
              "Svay Rieng",
              "Pursat",
              "Oddar Meanchey",
              "Preah Vihear",
              "Ratanakiri",
              "Mondulkiri",
              "Kratié",
              "Stung Treng",
              "Koh Kong",
              "Pailin",
            ],
          },
          {
            id: 44,
            country: "Senegal",
            states: [
              "Dakar",
              "Diourbel",
              "Thies",
              "Fatick",
              "Kaolack",
              "Kolda",
              "Louga",
              "Saint-Louis",
              "Matam",
              "Tambacounda",
              "Kaffrine",
              "Kedougou",
              "Ziguinchor",
            ],
          },
          {
            id: 45,
            country: "Chad",
            states: [
              "Batha",
              "Biltine",
              "Borkou",
              "Ennedi-Est",
              "Ennedi-Ouest",
              "Guera",
              "Hadjer-Lamis",
              "Kanem",
              "Lac",
              "Logone Occidental",
              "Logone Oriental",
              "Mandoul",
              "Mayo-Kebbi Est",
              "Mayo-Kebbi Ouest",
              "Moyen-Chari",
              "N'Djamena",
              "Ouaddai",
              "Salamat",
              "Sila",
              "Tandjile",
            ],
          },
          {
            id: 46,
            country: "Honduras",
            states: [
              "Atlantida",
              "Choluteca",
              "Colon",
              "Comayagua",
              "Copan",
              "Cortes",
              "El Paraiso",
              "Francisco Morazan",
              "Gracias a Dios",
              "Intibuca",
              "Islas de la Bahia",
              "La Paz",
              "Lempira",
              "Ocotepeque",
              "Olancho",
              "Santa Barbara",
              "Valle",
              "Yoro",
            ],
          },
          {
            id: 47,
            country: "Sierra Leone",
            states: ["Eastern", "Northern", "Southern", "Western"],
          },
          {
            id: 48,
            country: "El Salvador",
            states: [
              "Ahuachapan",
              "Cabanas",
              "Cuscatlan",
              "Chalatenango",
              "La Libertad",
              "La Paz",
              "La Union",
              "Morazan",
              "San Miguel",
              "San Salvador",
              "Santa Ana",
              "San Vicente",
              "Sonsonate",
              "Usulutan",
            ],
          },
          {
            id: 49,
            country: "Lebanon",
            states: [
              "Beirut",
              "Mount Lebanon",
              "North Governorate",
              "South Governorate",
              "Bekaa",
              "Nabatieh",
            ],
          },
          {
            id: 50,
            country: "Ghana",
            states: [
              "Greater Accra",
              "Ashanti",
              "Western",
              "Eastern",
              "Central",
              "Volta",
              "Brong-Ahafo",
              "Northern",
              "Upper East",
              "Upper West",
            ],
          },
          {
            id: 51,
            country: "South Africa",
            states: [
              "Gauteng",
              "KwaZulu-Natal",
              "Western Cape",
              "Eastern Cape",
              "Limpopo",
              "Mpumalanga",
              "North West",
              "Free State",
              "Northern Cape",
            ],
          },
          {
            id: 52,
            country: "Kenya",
            states: [
              "Nairobi",
              "Mombasa",
              "Kisumu",
              "Nakuru",
              "Eldoret",
              "Thika",
              "Kakamega",
              "Nyeri",
              "Meru",
              "Embu",
              "Machakos",
              "Kisii",
              "Bungoma",
            ],
          },
          {
            id: 53,
            country: "Italy",
            states: [
              "Lombardy",
              "Lazio",
              "Campania",
              "Sicily",
              "Veneto",
              "Piedmont",
              "Emilia-Romagna",
              "Tuscany",
              "Calabria",
              "Liguria",
              "Marche",
              "Abruzzo",
              "Friuli Venezia Giulia",
              "Umbria",
            ],
          },
          {
            id: 54,
            country: "Spain",
            states: [
              "Madrid",
              "Catalonia",
              "Andalusia",
              "Valencia",
              "Galicia",
              "Castile and León",
              "Basque Country",
              "Canary Islands",
              "Castilla-La Mancha",
              "Murcia",
              "Aragon",
              "Extremadura",
              "Balearic Islands",
              "Asturias",
              "Navarre",
            ],
          },
          {
            id: 55,
            country: "Portugal",
            states: [
              "Lisbon",
              "Porto",
              "Vila Nova de Gaia",
              "Amadora",
              "Braga",
              "Setubal",
              "Coimbra",
              "Queluz",
              "Funchal",
              "Cacem",
              "Vila Franca de Xira",
              "Loures",
              "Evora",
            ],
          },
          {
            id: 56,
            country: "Netherlands",
            states: [
              "North Holland",
              "South Holland",
              "North Brabant",
              "Gelderland",
              "Utrecht",
              "Overijssel",
              "Limburg",
              "Flevoland",
              "Groningen",
              "Drenthe",
              "Zeeland",
              "Fryslân",
            ],
          },
          {
            id: 57,
            country: "Belgium",
            states: [
              "Antwerp",
              "East Flanders",
              "West Flanders",
              "Hainaut",
              "Liège",
              "Limburg",
              "Luxembourg",
              "Namur",
              "Brussels-Capital Region",
              "Flemish Brabant",
              "Walloon Brabant",
            ],
          },
          {
            id: 58,
            country: "Switzerland",
            states: [
              "Zurich",
              "Bern",
              "Vaud",
              "Aargau",
              "Lucerne",
              "Geneva",
              "Basel-City",
              "Zug",
              "Ticino",
              "Fribourg",
              "Valais",
              "Neuchatel",
              "Solothurn",
              "St. Gallen",
              "Schaffhausen",
            ],
          },
          {
            id: 59,
            country: "Sweden",
            states: [
              "Stockholm",
              "Västra Götaland",
              "Skåne",
              "Östergötland",
              "Uppsala",
              "Värmland",
              "Halland",
              "Jönköping",
              "Norrbotten",
              "Dalarna",
              "Gävleborg",
              "Västernorrland",
              "Blekinge",
              "Kalmar",
              "Kronoberg",
            ],
          },
          {
            id: 60,
            country: "Norway",
            states: [
              "Oslo",
              "Viken",
              "Innlandet",
              "Vestfold og Telemark",
              "Agder",
              "Rogaland",
              "Vestland",
              "Møre og Romsdal",
              "Trøndelag",
              "Nordland",
              "Troms og Finnmark",
            ],
          },
          {
            id: 61,
            country: "Denmark",
            states: [
              "Capital Region of Denmark",
              "Central Denmark Region",
              "Region of Southern Denmark",
              "North Denmark Region",
            ],
          },
          {
            id: 62,
            country: "Finland",
            states: [
              "Uusimaa",
              "Varsinais-Suomi",
              "Satakunta",
              "Kanta-Häme",
              "Pirkanmaa",
              "Päijät-Häme",
              "Kymenlaakso",
              "South Karelia",
              "Etelä-Savo",
              "Pohjois-Savo",
              "North Karelia",
              "Central Finland",
              "South Ostrobothnia",
              "Ostrobothnia",
              "Kainuu",
              "Lapland",
            ],
          },
          {
            id: 63,
            country: "Ireland",
            states: [
              "Dublin",
              "Cork",
              "Limerick",
              "Galway",
              "Waterford",
              "Kilkenny",
              "Wexford",
              "Sligo",
              "Mayo",
              "Roscommon",
              "Kerry",
              "Donegal",
              "Louth",
            ],
          },
          {
            id: 64,
            country: "New Zealand",
            states: [
              "Auckland",
              "Wellington",
              "Canterbury",
              "Waikato",
              "Bay of Plenty",
              "Otago",
              "Manawatu-Wanganui",
              "Northland",
              "Hawke's Bay",
              "Taranaki",
              "Southland",
              "West Coast",
              "Gisborne",
            ],
          },
          {
            id: 65,
            country: "Austria",
            states: [
              "Vienna",
              "Lower Austria",
              "Upper Austria",
              "Styria",
              "Tyrol",
              "Carinthia",
              "Salzburg",
              "Vorarlberg",
              "Burgenland",
            ],
          },
          {
            id: 66,
            country: "Hungary",
            states: [
              "Budapest",
              "Pest",
              "Gyor-Moson-Sopron",
              "Hajdu-Bihar",
              "Szabolcs-Szatmar-Bereg",
              "Fejer",
              "Csongrad",
              "Bacs-Kiskun",
              "Veszprem",
              "Zala",
              "Baranya",
              "Tolna",
              "Komarom-Esztergom",
              "Somogy",
              "Heves",
              "Nograd",
              "Bekes",
              "Jasz-Nagykun-Szolnok",
              "Borsod-Abauj-Zemplen",
            ],
          },
          {
            id: 67,
            country: "Gambia",
            states: [
              "Banjul",
              "Lower River",
              "Central River",
              "North Bank",
              "Upper River",
              "Western",
              "North Bank East",
            ],
          },
          {
            id: 68,
            country: "Jamaica",
            states: [
              "Kingston",
              "St. Andrew",
              "St. Catherine",
              "Clarendon",
              "Manchester",
              "St. Elizabeth",
              "Westmoreland",
              "Hanover",
              "St. James",
              "Trelawny",
              "St. Ann",
              "St. Mary",
              "Portland",
            ],
          },
          {
            id: 69,
            country: "Bolivia",
            states: [
              "La Paz",
              "Santa Cruz",
              "Cochabamba",
              "Oruro",
              "Potosi",
              "Tarija",
              "Chuquisaca",
              "Beni",
              "Pando",
            ],
          },
          {
            id: 70,
            country: "Ecuador",
            states: [
              "Pichincha",
              "Guayas",
              "Azuay",
              "Manabi",
              "Santo Domingo de los Tsachilas",
              "El Oro",
              "Loja",
              "Tungurahua",
              "Esmeraldas",
              "Imbabura",
              "Cotopaxi",
              "Herrera",
              "Bolivar",
              "Galapagos",
              "Sucumbios",
              "Morona Santiago",
              "Napo",
              "Orellana",
              "Pastaza",
              "Santa Elena",
              "Zamora-Chinchipe",
            ],
          },
          {
            id: 71,
            country: "Peru",
            states: [
              "Lima",
              "Arequipa",
              "La Libertad",
              "Lambayeque",
              "Cusco",
              "Piura",
              "Puno",
              "Callao",
              "Loreto",
              "Junin",
              "San Martin",
              "Ancash",
              "Tacna",
              "Huanuco",
              "Ica",
              "Amazonas",
              "Cajamarca",
              "Ayacucho",
              "Ucayali",
              "Moquegua",
              "Pasco",
              "Madre de Dios",
              "Tumbes",
            ],
          },
          {
            id: 72,
            country: "Venezuela",
            states: [
              "Capital District",
              "Amazonas",
              "Anzoategui",
              "Apure",
              "Aragua",
              "Barinas",
              "Bolivar",
              "Carabobo",
              "Cojedes",
              "Delta Amacuro",
              "Falcon",
              "Guarico",
              "Lara",
              "Merida",
              "Miranda",
              "Monagas",
              "Nueva Esparta",
              "Portuguesa",
              "Sucre",
              "Tachira",
              "Trujillo",
              "Vargas",
              "Yaracuy",
              "Zulia",
            ],
          },
          {
            id: 73,
            country: "Chile",
            states: [
              "Santiago Metropolitan Region",
              "Valparaiso",
              "Biobio",
              "O'Higgins",
              "Maule",
              "Los Lagos",
              "Araucania",
              "Magallanes and Chilean Antarctica",
              "Los Rios",
              "Arica and Parinacota",
              "Antofagasta",
              "Tarapaca",
            ],
          },
          {
            id: 74,
            country: "Czech Republic",
            states: [
              "Prague",
              "Central Bohemian",
              "South Bohemian",
              "Plzen",
              "Karlovy Vary",
              "Usti nad Labem",
              "Liberec",
              "Hradec Kralove",
              "Pardubice",
              "Olomouc",
              "Moravian-Silesian",
              "South Moravian",
              "Zlin",
            ],
          },
          {
            id: 75,
            country: "Slovakia",
            states: [
              "Bratislava",
              "Trnava",
              "Trencin",
              "Nitra",
              "Zilina",
              "Banska Bystrica",
              "Presov",
              "Kosice",
            ],
          },
          {
            id: 76,
            country: "Singapore",
            states: ["Singapore"],
          },
          {
            id: 77,
            country: "Malawi",
            states: ["Northern Region", "Central Region", "Southern Region"],
          },
          {
            id: 78,
            country: "Rwanda",
            states: [
              "Kigali City",
              "Northern Province",
              "Southern Province",
              "Eastern Province",
              "Western Province",
            ],
          },
          {
            id: 79,
            country: "Mali",
            states: [
              "Bamako",
              "Kayes",
              "Koulikoro",
              "Sikasso",
              "Ségou",
              "Mopti",
              "Timbuktu",
              "Gao",
              "Kidal",
            ],
          },
          {
            id: 80,
            country: "Cuba",
            states: [
              "Havana",
              "Santiago de Cuba",
              "Camaguey",
              "Holguin",
              "Guantanamo",
              "Villa Clara",
              "Cienfuegos",
              "Sancti Spiritus",
              "Ciego de Avila",
              "Pinar del Rio",
              "Artemisa",
              "Mayabeque",
              "Las Tunas",
              "Granma",
              "Matanzas",
            ],
          },
          {
            id: 81,
            country: "United Kingdom",
            states: ["England", "Scotland", "Wales", "Northern Ireland"],
          },
          {
            id: 82,
            country: "South Sudan",
            states: [
              "Central Equatoria",
              "Eastern Equatoria",
              "Jonglei",
              "Lakes",
              "Northern Bahr el Ghazal",
              "Unity",
              "Upper Nile",
              "Warrap",
              "Western Bahr el Ghazal",
              "Western Equatoria",
            ],
          },
          {
            id: 83,
            country: "Fiji",
            states: [
              "Central Division",
              "Eastern Division",
              "Northern Division",
              "Western Division",
            ],
          },
          {
            id: 84,
            country: "Romania",
            states: [
              "Muntenia",
              "Transylvania",
              "Moldova",
              "Banat",
              "Crisana",
              "Dobrogea",
              "Maramures",
              "Oltenia",
              "Slovakia",
            ],
          },
          {
            id: 85,
            country: "Gambia",
            states: [
              "Banjul",
              "Lower River",
              "Central River",
              "North Bank",
              "Upper River",
              "Western",
              "North Bank East",
            ],
          },
          {
            id: 86,
            country: "Sri Lanka",
            states: [
              "Western Province",
              "Central Province",
              "Southern Province",
              "Northern Province",
              "Eastern Province",
              "North Western Province",
              "North Central Province",
              "Uva Province",
              "Sabaragamuwa Province",
            ],
          },
          {
            id: 87,
            country: "Tunisia",
            states: [
              "Tunis",
              "Ariana",
              "Ben Arous",
              "Manouba",
              "Nabeul",
              "Zaghouan",
              "Bizerte",
              "Beja",
              "Jendouba",
              "Le Kef",
              "Siliana",
              "Kairouan",
              "Kasserine",
              "Sidi Bouzid",
              "Sfax",
              "Gabes",
              "Medenine",
              "Tataouine",
              "Gafsa",
              "Tozeur",
            ],
          },
          {
            id: 88,
            country: "Estonia",
            states: [
              "Harju County",
              "Hiiu County",
              "Ida-Viru County",
              "Järva County",
              "Jõgeva County",
              "Lääne County",
              "Lääne-Viru County",
              "Pärnu County",
              "Põlva County",
              "Rapla County",
              "Saare County",
              "Tartu County",
              "Valga County",
              "Viljandi County",
              "Võru County",
            ],
          },
          {
            id: 89,
            country: "Niger",
            states: [
              "Agadez",
              "Diffa",
              "Dosso",
              "Maradi",
              "Tahoua",
              "Tillabéri",
              "Zinder",
            ],
          },
          {
            id: 90,
            country: "Botswana",
            states: [
              "Central District",
              "Chobe District",
              "Ghanzi District",
              "Kgalagadi District",
              "Kgatleng District",
              "Kweneng District",
              "North-East District",
              "North-West District",
              "Southern District",
            ],
          },
          {
            id: 91,
            country: "Mauritania",
            states: [
              "Hodh Ech Chargui",
              "Hodh El Gharbi",
              "Assaba",
              "Gorgol",
              "Brakna",
              "Trarza",
              "Adrar",
              "Dakhlet Nouadhibou",
              "Tagant",
              "Guidimaka",
              "Tiris Zemmour",
              "Inchiri",
              "Nouakchott",
            ],
          },
          {
            id: 92,
            country: "Cyprus",
            states: ["Nicosia", "Limassol", "Larnaca", "Famagusta", "Paphos"],
          },
          {
            id: 93,
            country: "Trinidad and Tobago",
            states: [
              "Port of Spain",
              "San Fernando",
              "Arima",
              "Point Fortin",
              "Chaguanas",
              "Tunapuna-Piarco",
              "San Juan-Laventille",
              "Sangre Grande",
              "Princes Town",
              "Couva-Tabaquite-Talparo",
              "Penal-Debe",
              "Siparia",
            ],
          },
          {
            id: 94,
            country: "Barbados",
            states: [
              "Saint Michael",
              "Saint Thomas",
              "Saint James",
              "Saint Peter",
              "Saint Andrew",
              "Saint Joseph",
              "Saint John",
            ],
          },
          {
            id: 95,
            country: "Bahrain",
            states: [
              "Capital Governorate",
              "Muharraq Governorate",
              "Northern Governorate",
              "Southern Governorate",
            ],
          },
          {
            id: 96,
            country: "Luxembourg",
            states: ["Luxembourg", "Diekirch", "Grevenmacher"],
          },
          {
            id: 97,
            country: "Liberia",
            states: [
              "Bomi",
              "Bong",
              "Gbarpolu",
              "Grand Bassa",
              "Grand Cape Mount",
              "Grand Gedeh",
              "Grand Kru",
              "Lofa",
              "Margibi",
              "Maryland",
              "Montserrado",
              "Nimba",
              "River Cess",
              "River Gee",
              "Sinoe",
            ],
          },
          {
            id: 98,
            country: "Lesotho",
            states: [
              "Maseru",
              "Butha-Buthe",
              "Leribe",
              "Berea",
              "Mafeteng",
              "Mohale's Hoek",
              "Quthing",
              "Qacha's Nek",
            ],
          },
          {
            id: 99,
            country: "San Marino",
            states: ["San Marino"],
          },
          {
            id: 100,
            country: "Eswatini",
            states: ["Hhohho", "Lubombo", "Manzini", "Shiselweni"],
          },
        ];
        res.json(allCountries);
      };
      
      const allCountryDialingCode = (req, res) => {
        const allCountries = [
          {
            id: 1,
            country: "China",
            code: "+86"
          },
          {
            id: 2,
            country: "India",
            code: "+91"
          },
          {
            id: 3,
            country: "United States",
            code: "+1"
          },
          {
            id: 4,
            country: "Indonesia",
            code: "+62"
          },
          {
            id: 5,
            country: "Pakistan",
            code: "+92"
          },
          {
            id: 6,
            country: "Brazil",
            code: "+55"
          },
          {
            id: 7,
            country: "Bangladesh",
            code: "+880"
          },
          {
            id: 8,
            country: "Nigeria",
            code: "+234"
          },
          {
            id: 9,
            country: "Russia",
            code: "+7"
          },
          {
            id: 10,
            country: "Japan",
            code: "+81"
          },
          {
            id: 11,
            country: "Mexico",
            code: "+52"
          },
          {
            id: 12,
            country: "Philippines",
            code: "+63"
          },
          {
            id: 13,
            country: "Vietnam",
            code: "+84"
          },
          {
            id: 14,
            country: "Ethiopia",
            code: "+251"
          },
          {
            id: 15,
            country: "Egypt",
            code: "+20"
          },
          {
            id: 16,
            country: "Germany",
            code: "+49"
          },
          {
            id: 17,
            country: "Iran",
            code: "+98"
          },
          {
            id: 18,
            country: "Turkey",
            code: "+90"
          },
          {
            id: 19,
            country: "Thailand",
            code: "+66"
          },
          {
            id: 20,
            country: "France",
            code: "+33"
          },
          {
            id: 21,
            country: "South Korea",
            code: "+82"
          },
          {
            id: 22,
            country: "Argentina",
            code: "+54"
          },
          {
            id: 23,
            country: "Myanmar",
            code: "+95"
          },
          {
            id: 24,
            country: "Ukraine",
            code: "+380"
          },
          {
            id: 25,
            country: "Sudan",
            code: "+249"
          },
          {
            id: 26,
            country: "Uganda",
            code: "+256"
          },
          {
            id: 27,
            country: "Iraq",
            code: "+964"
          },
          {
            id: 28,
            country: "Poland",
            code: "+48"
          },
          {
            id: 29,
            country: "Canada",
            code: "+1"
          },
          {
            id: 30,
            country: "Malaysia",
            code: "+60"
          },
          {
            id: 31,
            country: "Greece",
            code: "+30"
          },
          {
            id: 32,
            country: "Morocco",
            code: "+212"
          },
          {
            id: 33,
            country: "Saudi Arabia",
            code: "+966"
          },
          {
            id: 34,
            country: "Madagascar",
            code: "+261"
          },
          {
            id: 35,
            country: "Cameroon",
            code: "+237"
          },
          {
            id: 36,
            country: "Cote d'Ivoire",
            code: "+225"
          },
          {
            id: 37,
            country: "Australia",
            code: "+61"
          },
          {
            id: 38,
            country: "Kazakhstan",
            code: "+7"
          },
          {
            id: 39,
            country: "Nepal",
            code: "+977"
          },
          {
            id: 40,
            country: "Zimbabwe",
            code: "+263"
          },
          {
            id: 41,
            country: "Yemen",
            code: "+967"
          },
          {
            id: 42,
            country: "Mozambique",
            code: "+258"
          },
          {
            id: 43,
            country: "Cambodia",
            code: "+855"
          },
          {
            id: 44,
            country: "Senegal",
            code: "+221"
          },
          {
            id: 45,
            country: "Chad",
            code: "+235"
          },
          {
            id: 46,
            country: "Honduras",
            code: "+504"
          },
          {
            id: 47,
            country: "Sierra Leone",
            code: "+232"
          },
          {
            id: 48,
            country: "El Salvador",
            code: "+503"
          },
          {
            id: 49,
            country: "Lebanon",
            code: "+961"
          },
          {
            id: 50,
            country: "Ghana",
            code: "+233"
          },
          {
            id: 51,
            country: "South Africa",
            code: "+27"
          },
          {
            id: 52,
            country: "Kenya",
            code: "+254"
          },
          {
            id: 53,
            country: "Italy",
            code: "+39"
          },
          {
            id: 54,
            country: "Spain",
            code: "+34"
          },
          {
            id: 55,
            country: "Portugal",
            code: "+351"
          },
          {
            id: 56,
            country: "Netherlands",
            code: "+31"
          },
          {
            id: 57,
            country: "Belgium",
            code: "+32"
          },
          {
            id: 58,
            country: "Switzerland",
            code: "+41"
          },
          {
            id: 59,
            country: "Sweden",
            code: "+46"
          },
          {
            id: 60,
            country: "Norway",
            code: "+47"
          },
          {
            id: 61,
            country: "Denmark",
            code: "+45"
          },
          {
            id: 62,
            country: "Finland",
            code: "+358"
          },
          {
            id: 63,
            country: "Ireland",
            code: "+353"
          },
          {
            id: 64,
            country: "New Zealand",
            code: "+64"
          },
          {
            id: 65,
            country: "Austria",
            code: "+43"
          },
          {
            id: 66,
            country: "Hungary",
            code: "+36"
          },
          {
            id: 67,
            country: "Gambia",
            code: "+220"
          },
          {
            id: 68,
            country: "Jamaica",
            code: "+1"
          },
          {
            id: 69,
            country: "Bolivia",
            code: "+591"
          },
          {
            id: 70,
            country: "Ecuador",
            code: "+593"
          },
          {
            id: 71,
            country: "Peru",
            code: "+51"
          },
          {
            id: 72,
            country: "Venezuela",
            code: "+58"
          },
          {
            id: 73,
            country: "Chile",
            code: "+56"
          },
          {
            id: 74,
            country: "Czech Republic",
            code: "+420"
          },
          {
            id: 75,
            country: "Slovakia",
            code: "+421"
          },
          {
            id: 76,
            country: "Singapore",
            code: "+65"
          },
          {
            id: 77,
            country: "Malawi",
            code: "+265"
          },
          {
            id: 78,
            country: "Rwanda",
            code: "+250"
          },
          {
            id: 79,
            country: "Mali",
            code: "+223"
          },
          {
            id: 80,
            country: "Cuba",
            code: "+53"
          },
          {
            id: 81,
            country: "United Kingdom",
            code: "+44"
          },
          {
            id: 82,
            country: "South Sudan",
            code: "+211"
          },
          {
            id: 83,
            country: "Fiji",
            code: "+679"
          },
          {
            id: 84,
            country: "Romania",
            code: "+40"
          },
          {
            id: 85,
            country: "Sri Lanka",
            code: "+94"
          },
          {
            id: 86,
            country: "Tunisia",
            code: "+216"
          },
          {
            id: 87,
            country: "Estonia",
            code: "+372"
          },
          {
            id: 88,
            country: "Niger",
            code: "+227"
          },
          {
            id: 89,
            country: "Botswana",
            code: "+267"
          },
          {
            id: 90,
            country: "Mauritania",
            code: "+222"
          },
          {
            id: 91,
            country: "Cyprus",
            code: "+357"
          },
          {
            id: 92,
            country: "Trinidad and Tobago",
            code: "+1"
          },
          {
            id: 93,
            country: "Barbados",
            code: "+1"
          },
          {
            id: 94,
            country: "Bahrain",
            code: "+973"
          },
          {
            id: 95,
            country: "Luxembourg",
            code: "+352"
          },
          {
            id: 96,
            country: "Liberia",
            code: "+231"
          },
          {
            id: 97,
            country: "Lesotho",
            code: "+266"
          },
          {
            id: 98,
            country: "San Marino",
            code: "+378"
          },
          {
            id: 99,
            country: "Eswatini",
            code: "+268"
          }
        ];
      
        res.json(allCountries);
      };
      
      module.exports = {
        allCountryAPI,
        allCountryDialingCode
      };